### ISSUE TITLE
Composite recording problems

### ISSUE THREAD

**Issue by davidrodriguezalfayate** [Kurento/bugtracker#6] opened 2015-10-16 17:56 UTC
<h2>Backgrounds</h2>
Composite is used only to record video from one user and audio for the rest of logged on users.<br/>
Composite is not used to deliver video nor audio to the logged on users, these negotiate independent WebRTC stream for each logged on user with the KMS

<h2>Detailed description</h2>
I have made several tests involving composite & hubport creation order:
<ul>
<li>Creating the composite when there are, at least, two logged on users</li>
<li>Creating the composite when creating pipeline but recorder when there are, at least, two logged on users</li>
<li>Defer hubport creation when there are, at least, two logged on users</li>
</ul>
In all these cases I can see a "black screen and no audio" during several seconds, the number of seconds is equal to the ellapsed time between "pipeline creation" and all "composite-recording infraestructure" initialization.

Apparently it should work if I create all "composite-recording infraestructure" when creating pipeline, and delaying recording to the moment that there are "at-least" two logged-on users. Unfortunately I have seen inconsistent behavior and also black screen.

<h2>Comparison with standalone recording features</h2>
If recorder is created for an individual webrtc stream (audio or audio&video) these problems not appear, you can create recorder whenever you want.

<h2>Workaround</h2>
Record each file in an indepedent way, use ffmpeg to combine files, invoking it from an embedded REST Server - as Jersey -

<h2>More information</h2>
This issue and detailed information could be seen in https://groups.google.com/forum/#!topic/kurento/FgHTaRYyp80

**Comment by igracia** [comment] 2015-10-16 21:30
We are creating a number of tests for the recorder precisely. I'll see if we can reproduce this in our test environment, so we can debug that. Thanks for the detailed report!

I hope we can give more info during the next week.

**Comment by jcaden** [comment] 2015-11-23 11:31
Hi, we have been working on improving composite and recorder. Could you check if the issue is fixed for you using the dev version?

**Comment by davidrodriguezalfayate** [comment] 2015-11-24 15:26
I'll give it a try as soon as possible, is dev version published or do I
have to compile it?

2015-11-23 12:31 GMT+01:00 José Antonio Santos Cadenas <
notifications@github.com>:

**Comment by igracia** [comment] 2015-11-24 15:29
Have a look at the documentation [here](https://doc-kurento.readthedocs.org/en/latest/mastering/kurento_development.html)

**Comment by jcaden** [comment] 2015-11-27 10:04
You can also use version 6.2.0 that we released recently. This one has also the fixes for composite and recorder.

**Comment by davidrodriguezalfayate** [comment] 2015-12-09 09:05
Apparently it works properly, I have to make further tests, but I think you have spotted on the problem

**Comment by igracia** [comment] 2015-12-09 09:51
Can we close the issue then?

**Comment by davidrodriguezalfayate** [comment] 2015-12-09 09:57
Sure

**Closed** 2015-12-09 09:58 UTC
Labels: bug, kms
