### ISSUE TITLE
Kurento can not support h264 RTSP video source with MPEG-2 transport(MP2T)

### ISSUE THREAD

**Issue by Nileshwagh22** [Kurento/bugtracker#119] opened 2016-08-24 05:05 UTC
I have successfully tested Kurento media server with raw h264 RTSP stream from file using Live555(RTSP server) Library to WebRTC stream on browser.

But in real time we have h264 RTSP stream with MPEG-2 transport (MP2T), I am streaming it using Live555 and access using VLC media player.It works fine. But when I pass h264 RTSP stream with MPEG-2 transport(RTSP url) to PlayerEndpoint of KMS and access using WebRtcEndpoint on browser, it does not work.

Please can you verify, what is problem with MPEG-2 transport(MP2T) RTSP video stream?

I have tested it on Kurento Media Server 6.4.0

**Comment by jcaden** [comment] 2016-08-24 10:57
Please, for further bug reports, use the template we provide. This way we don't need to ask a bunch of information all the time, it should be included in the report.

Can you provide the exact versions of the libraries that you are using? (dpkg command in the template)

Can you try with latest development version?

Can you provide a rtsp source (or a simple way to generate it) that makes kms fail?

**Comment by igracia** [comment] 2016-10-03 08:48
We have made tests with several different sources available, and couldn't reproduce this crash.

@jcaden I think we can close this, as it is not reproducible and seems isolated.

**Comment by jcaden** [comment] 2016-10-03 09:26
Thanks @igracia

**Closed by jcaden** 2016-10-03 09:26 UTC
