### ISSUE TITLE
I want push stream in a room to live555, red5, etc. how to get video stream addresses in a room? 

### ISSUE THREAD

**Issue by ustcck** [Kurento/bugtracker#396] opened 2019-08-20 12:15 UTC
**KMS Version**: 6.11.1. use docker 
**coturn Version**: lastest. use docker

I'm running this example:  kurento-tutorial-java/kurento-one2one-call-advanced

I want get a RTSP/RTMP/RTP stream address(like rtmp://<IP>:1935/live/livestream , rtsp://<IP>:554/stream), all can see this stream.

if not, I want get some suggestions.

**Comment by micaelgallego** [comment] 2019-08-20 15:46
Kurento doesn't support publishing its streams with RTSP or RTMP. 

You will have to use RTP to ffmpeg to RTMP.

**Comment by ustcck** [comment] 2019-08-21 01:31
Thanks. but how to get this RTP stream address in a room? like rtp://ip:port

**Comment by j1elo** [comment] 2019-08-21 10:51
You will have to connect an [RtpEndpoint](https://doc-kurento.readthedocs.io/en/latest/_static/client-javadoc/org/kurento/client/RtpEndpoint.html) in the Kurento Pipeline. Then, configure the RtpEndpoint with an SDP Offer, in which you state the codecs, and destination IP and Port.

There is an [RTP Receiver](https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-rtp-receiver.html) tutorial that can be useful to grasp these concepts. What you need is the opposite, to send RTP from RtpEndpoint.

**Comment by ustcck** [comment] 2019-08-22 09:24
I'm running this example: kurento-tutorial-java/kurento-rtp-receiver

`[root@localhost ~]# docker run -d --name kms -p 8888:8888 -e KMS_TURN_URL=kurento:kurento@10.4.65.57:3478 -e GST_DEBUG="Kurento*:5" kurento/kurento-media-server`

this way is ok，but IP is 172.17.0.3
`v=0
o=- 3775453860 3775453860 IN IP4 172.17.0.3
s=Kurento Media Server
c=IN IP4 172.17.0.3
t=0 0
m=audio 59652 RTP/AVPF 96
a=recvonly
a=rtpmap:96 opus/48000/2
a=direction:passive
a=ssrc:2647723633 cname:user3820876280@host-5be9fd96
m=video 56608 RTP/AVPF 103
a=recvonly
a=rtpmap:103 H264/90000
a=rtcp-fb:103 goog-remb
a=direction:passive
a=ssrc:4211332486 cname:user3820876280@host-5be9fd96`

so I change the network_mode by using ‘--net host’

`[root@localhost ~]# docker run -d --net host --name kms -e KMS_TURN_URL=kurento:kurento@10.4.65.57:3478 -e GST_DEBUG="Kurento*:5" kurento/kurento-media-server`

but I got an error，here is my log when I ran kurento-tutorial-java/kurento-hello-world

`2019-08-22 16:57:16.911  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleStart] New WebRtcEndpoint: user0052fe88-8a1d-6d64-5bc7-5fe26969632e_webrtcendpoint
2019-08-22 16:57:26.916 ERROR 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] Exception: org.kurento.jsonrpc.JsonRpcException: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":20,"method":"invoke","params":{"object":"60bebe99-c917-4ffa-9217-26bd8f3efa3d_kurento.MediaPipeline/898bab57-0f2c-4a5b-a2f1-a6c9be4cee57_kurento.WebRtcEndpoint","operation":"gatherCandidates","sessionId":"c3e1eed7-5014-407c-9036-e67eeea8c657"},"jsonrpc":"2.0"}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:26.917 ERROR 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Kurento] Exception: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":20,"method":"invoke","params":{"object":"60bebe99-c917-4ffa-9217-26bd8f3efa3d_kurento.MediaPipeline/898bab57-0f2c-4a5b-a2f1-a6c9be4cee57_kurento.WebRtcEndpoint","operation":"gatherCandidates","sessionId":"c3e1eed7-5014-407c-9036-e67eeea8c657"},"jsonrpc":"2.0"}
2019-08-22 16:57:26.918  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:0 1 UDP 2122252543 192.168.31.1 60350 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:36.920 ERROR 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] Exception: org.kurento.jsonrpc.JsonRpcException: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":21,"method":"invoke","params":{"object":"60bebe99-c917-4ffa-9217-26bd8f3efa3d_kurento.MediaPipeline/898bab57-0f2c-4a5b-a2f1-a6c9be4cee57_kurento.WebRtcEndpoint","operation":"addIceCandidate","operationParams":{"candidate":{"sdpMLineIndex":0,"candidate":"candidate:0 1 UDP 2122252543 192.168.31.1 60350 typ host","__type__":"IceCandidate","sdpMid":"0","__module__":"kurento"}},"sessionId":"c3e1eed7-5014-407c-9036-e67eeea8c657"},"jsonrpc":"2.0"}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:36.921 ERROR 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Kurento] Exception: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":21,"method":"invoke","params":{"object":"60bebe99-c917-4ffa-9217-26bd8f3efa3d_kurento.MediaPipeline/898bab57-0f2c-4a5b-a2f1-a6c9be4cee57_kurento.WebRtcEndpoint","operation":"addIceCandidate","operationParams":{"candidate":{"sdpMLineIndex":0,"candidate":"candidate:0 1 UDP 2122252543 192.168.31.1 60350 typ host","__type__":"IceCandidate","sdpMid":"0","__module__":"kurento"}},"sessionId":"c3e1eed7-5014-407c-9036-e67eeea8c657"},"jsonrpc":"2.0"}
2019-08-22 16:57:36.923  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:3 1 UDP 2122187007 10.106.23.172 60351 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:46.926 ERROR 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] Exception: org.kurento.jsonrpc.JsonRpcException: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":22,"method":"invoke","params":{"object":"60bebe99-c917-4ffa-9217-26bd8f3efa3d_kurento.MediaPipeline/898bab57-0f2c-4a5b-a2f1-a6c9be4cee57_kurento.WebRtcEndpoint","operation":"addIceCandidate","operationParams":{"candidate":{"sdpMLineIndex":0,"candidate":"candidate:3 1 UDP 2122187007 10.106.23.172 60351 typ host","__type__":"IceCandidate","sdpMid":"0","__module__":"kurento"}},"sessionId":"c3e1eed7-5014-407c-9036-e67eeea8c657"},"jsonrpc":"2.0"}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:46.926 ERROR 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Kurento] Exception: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":22,"method":"invoke","params":{"object":"60bebe99-c917-4ffa-9217-26bd8f3efa3d_kurento.MediaPipeline/898bab57-0f2c-4a5b-a2f1-a6c9be4cee57_kurento.WebRtcEndpoint","operation":"addIceCandidate","operationParams":{"candidate":{"sdpMLineIndex":0,"candidate":"candidate:3 1 UDP 2122187007 10.106.23.172 60351 typ host","__type__":"IceCandidate","sdpMid":"0","__module__":"kurento"}},"sessionId":"c3e1eed7-5014-407c-9036-e67eeea8c657"},"jsonrpc":"2.0"}
2019-08-22 16:57:46.926  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:6 1 TCP 2105524479 192.168.31.1 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.637  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:7 1 TCP 2105458943 10.106.23.172 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.659  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:0 2 UDP 2122252542 192.168.31.1 60352 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.662  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:3 2 UDP 2122187006 10.106.23.172 60353 typ host","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.666  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:6 2 TCP 2105524478 192.168.31.1 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.710  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:7 2 TCP 2105458942 10.106.23.172 9 typ host tcptype active","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.713  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:0 1 UDP 2122252543 192.168.31.1 60354 typ host","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.717  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:3 1 UDP 2122187007 10.106.23.172 60355 typ host","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.721  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:6 1 TCP 2105524479 192.168.31.1 9 typ host tcptype active","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.725  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:7 1 TCP 2105458943 10.106.23.172 9 typ host tcptype active","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.727  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:0 2 UDP 2122252542 192.168.31.1 60356 typ host","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.731  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:3 2 UDP 2122187006 10.106.23.172 60357 typ host","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.734  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:6 2 TCP 2105524478 192.168.31.1 9 typ host tcptype active","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.737  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:7 2 TCP 2105458942 10.106.23.172 9 typ host tcptype active","sdpMid":"1","sdpMLineIndex":1,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.741  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:4 1 UDP 1685987327 58.247.171.4 49069 typ srflx raddr 10.106.23.172 rport 60351","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.745  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"ADD_ICE_CANDIDATE","candidate":{"candidate":"candidate:4 2 UDP 1685987326 58.247.171.4 21378 typ srflx raddr 10.106.23.172 rport 60353","sdpMid":"0","sdpMLineIndex":0,"usernameFragment":"67d29115"}}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.749  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::handleTextMessage] message: {"id":"STOP"}, sessionId: 0052fe88-8a1d-6d64-5bc7-5fe26969632e
2019-08-22 16:57:50.749  INFO 16096 --- [nio-8443-exec-2] org.kurento.tutorial.helloworld.Handler  : [Handler::stop] Release the Media Pipeline
`

**Comment by j1elo** [comment] 2019-09-05 09:35
I'd recommend running in local so there are no other network layers or issues introduced with Docker. 

When everything is running OK, then you worry about moving to Docker and configuring your container to work (which can be tricky sometimes but that's a Docker issue, not Kurento)

**Comment by j1elo** [comment] 2019-09-05 09:36
Closing because this is not a bug (if you still have questions I'm sure some people in the [community forums](https://doc-kurento.readthedocs.io/en/latest/user/support.html#community-support) will be able to help)

**Closed by j1elo** 2019-09-05 09:36 UTC
