### ISSUE TITLE
Removing not supported codec 'OPUS/48000/2'

### ISSUE THREAD

**Issue by adrianbg** [Kurento/bugtracker#23] opened 2016-01-26 06:53 UTC
From https://groups.google.com/forum/#!topic/kurento/NiqUtyXgZPw

Ubuntu: 14.04
kurento-media-server-6.0: 6.3.1.trusty
kms-core-6.0: 6.3.0.trusty
App server is the Hello World tutorial from git, version 6.1.0.

KMS incorrectly rejects OPUS when responding to this SDP offer:

v=0
o=- 1453762830611886000 1 IN IP4 127.0.0.1
s=-
t=0 0
m=audio 9 UDP/TLS/RTP/SAVPF 111 8 0
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendrecv
a=rtpmap:111 OPUS/48000/2
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=ice-ufrag:ZfjL
a=ice-pwd:wiaY1VPsHvoJuKehvpHvcd
a=candidate:1 1 UDP 2013266431 192.168.0.109 62741 typ host
a=candidate:2 1 TCP 1019216383 192.168.0.109 0 typ host tcptype active
a=candidate:3 1 TCP 1015022079 192.168.0.109 59776 typ host tcptype passive
a=candidate:4 1 UDP 2013266431 21.57.2.200 59013 typ host
a=candidate:5 1 TCP 1019216383 21.57.2.200 0 typ host tcptype active
a=candidate:6 1 TCP 1015022079 21.57.2.200 59777 typ host tcptype passive
a=candidate:7 1 UDP 1677722111 104.193.168.123 62741 typ srflx raddr 192.168.0.109 rport 62741
a=candidate:8 1 TCP 847249919 104.193.168.123 0 typ srflx raddr 192.168.0.109 rport 0 tcptype active
a=candidate:9 1 TCP 843055615 104.193.168.123 59776 typ srflx raddr 192.168.0.109 rport 59776 tcptype passive
a=candidate:10 1 UDP 167772671 52.34.12.79 52204 typ relay raddr 192.168.0.109 rport 62741
a=candidate:11 1 UDP 1677722111 172.56.38.55 23575 typ srflx raddr 21.57.2.200 rport 59013
a=candidate:12 1 TCP 847249919 172.56.38.55 0 typ srflx raddr 21.57.2.200 rport 0 tcptype active
a=candidate:13 1 TCP 843055615 172.56.38.55 59777 typ srflx raddr 21.57.2.200 rport 59777 tcptype passive
a=candidate:14 1 UDP 167772671 52.34.12.79 52540 typ relay raddr 21.57.2.200 rport 59013
a=fingerprint:sha-256 1B:9B:75:82:12:6F:62:6E:13:9D:44:08:98:FD:1B:B7:59:90:42:D9:21:B5:D5:BF:2D:12:A2:5E:42:D6:1B:32
a=setup:actpass

**The following messages appear in the logs:**

2016-01-26 06:01:11,240765 29536 [0x00007f7d93fff700]    info KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:68 remove_not_supported_codecs_from_array() <kmswebrtcendpoint0>  Removing not supported codec 'OPUS/48000/2'
2016-01-26 06:01:11,241005 29536 [0x00007f7d93fff700]    info KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:68 remove_not_supported_codecs_from_array() <kmswebrtcendpoint0>  Removing not supported codec 'AMR/8000'
2016-01-26 06:01:11,241133 29536 [0x00007f7d93fff700]    info KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:68 remove_not_supported_codecs_from_array() <kmswebrtcendpoint0>  Removing not supported codec 'H264/90000'

**Here is SdpEndpoint.conf.json:**

{
  "numAudioMedias" : 1,
  "numVideoMedias" : 1,
  "audioCodecs" : [
    {
      "name" : "OPUS/48000/2"
// Next is an example about how a codec can be configured.
// WARNING: Usage of properties is not yet supported
//      "properties" : {
//        "maxcodedaudiobandwidth" : "16000",
//        "maxaveragebitrate" : "20000",
//        "stereo": "1",
//        "useinbandfec" : "1",
//        "usedtx" : "0"
//      }
    },
    {
      "name" : "PCMU/8000"
    },
    {
      "name" : "AMR/8000"
    }
  ],
  "videoCodecs" : [
    {
      "name" : "VP8/90000"
    },
    {
      "name" : "H264/90000"
    }
  ]
}

**sdp_pattern.txt:**

v=0
o=- 0 0 IN IP4 0.0.0.0
s=Kurento Media Server
c=IN IP4 0.0.0.0
t=0 0
m=audio 0 RTP/AVP 111 99 0
a=rtpmap:111 OPUS/48000/2
a=rtpmap:99 AMR/8000/1
a=rtpmap:0 PCMU/8000
m=video 0 RTP/AVP 96 97 100 101
a=rtpmap:96 H263-1998/90000
a=rtpmap:97 VP8/90000
a=rtpmap:100 MP4V-ES/90000
a=rtpmap:101 H264/90000

**Comment by jcaden** [comment] 2016-01-26 07:19
As I said in the list, I think that the problem is caused by opus written in capital letters. If you try again mangling the sdp before passing it to kms changing OPUS by opus it should work. In the meantime we'll try to fix it.

**Comment by adrianbg** [comment] 2016-01-26 07:20
Sorry, I didn't see your comment in the list.

But actually I've already tried that. It didn't help

**Comment by adrianbg** [comment] 2016-01-26 07:33
You're right. Mangling my SDP offer did fix this issue. I think it didn't work the last time I tried because I had OPUS capitalized in my Kurento configuration. Thanks for your help.

**Comment by igracia** [comment] 2016-01-26 09:17
@adrianbg I'm closing this issue, then.

**Comment by jcaden** [comment] 2016-01-26 09:35
Please @igracia let it open because mediaserver should not reject this offers an no mangling should be necessary.

**Comment by igracia** [comment] 2016-01-26 09:37
Sure! Sorry for closing too early.

**Comment by jcaden** [comment] 2016-02-01 10:18
Fixed on since 6.3.2

**Closed by jcaden** 2016-02-01 10:18 UTC
Labels: bug, kms
