### ISSUE TITLE
KMS when to  supports cluster

### ISSUE THREAD

**Issue by lizige** [Kurento/bugtracker#495] opened 2020-07-02 00:53 UTC
KMS when to  supports cluster

**Comment by j1elo** [comment] 2020-07-02 15:59
Kurento is a service. You write your own cluster with the services you need. Or use an already existing solution, like OpenVidu
https://docs.openvidu.io/en/2.14.0/openvidu-pro/scalability/

Closing issue: Not a bug.

**Closed by j1elo** 2020-07-02 15:59 UTC
Labels: not-a-bug
