### ISSUE TITLE
crash on gst_bus_source_dispatch 

### ISSUE THREAD

**Issue by darrenhp** [Kurento/bugtracker#509] opened 2020-07-26 16:18 UTC
## Prerequisites

* [x] I have read the SUPPORT document
  

* [x] I have checked the Troubleshooting Guide
  

* [x] I have tested with the latest version of Kurento
  

## Context

Segmentation fault (thread 139752679604864, pid 1197)
Stack trace:
[magazine_cache_trim]
glib/gslice.c:679
[thread_memory_magazine2_unload]
glib/gslice.c:810
[_gst_message_free]
./gst/gstmessage.c:213
[gst_bus_source_dispatch]
./gst/gstbus.c:794
[g_main_dispatch]
glib/gmain.c:3180
[g_main_context_iterate]
glib/gmain.c:3902
[g_main_loop_run]
glib/gmain.c:4097
[??]
??:0
0x560A8F40FEE4 at /usr/bin/kurento-media-server
[__libc_start_main]
csu/libc-start.c:344
[??]
??:0
0x560A8F411DFA at /usr/bin/kurento-media-server

I'm sorry that I found no "CoreDump" after unpack the _usr_bin_kurento-media-server.1000.crash;
May be the ulimit -c is too small;  
```
$ ulimit -c
1024000
```
### INFO about Kurento Media Server

* Kurento version:   6.14.0
* Server OS:         18.04
* Installation method:
    
  - [x] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:                 
* Kurento Client version:   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```
```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

$ kurento-media-server --version
Kurento Media Server version: 6.14.0
Found modules:
        'core' version 6.14.0
        'elements' version 6.14.0
        'filters' version 6.14.0

$ dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
ii  gstreamer1.5-alsa:amd64                1.8.1-1kurento2.18.04                           amd64        GStreamer plugin for ALSA
ii  gstreamer1.5-libav:amd64               1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer
ii  gstreamer1.5-libav-dbg:amd64           1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer (debug symbols)
ii  gstreamer1.5-nice:amd64                0.1.17-0kurento1.18.04                          amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-nice-dbgsym:amd64         0.1.17-0kurento1.18.04                          amd64        debug symbols for gstreamer1.5-nice
ii  gstreamer1.5-plugins-bad:amd64         1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-bad-dbg:amd64     1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "bad" set (debug symbols)
ii  gstreamer1.5-plugins-base:amd64        1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-base-dbg:amd64    1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64        1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-good-dbg:amd64    1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64        1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-plugins-ugly-dbg:amd64    1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set (debug symbols)
ii  gstreamer1.5-pulseaudio:amd64          1.8.1-1kurento4.18.04                           amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                   1.8.1-1kurento2.18.04                           amd64        GStreamer plugins for X11 and Pango
ii  kms-core                               6.14.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-core-dbg                           6.14.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-elements                           6.14.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-elements-dbg                       6.14.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-filters                            6.14.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-filters-dbg                        6.14.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-jsonrpc                            6.14.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kms-jsonrpc-dbg                        6.14.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                             1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dbg                         1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kurento-dbg                            6.14.0-0kurento1.18.04                          amd64        Meta-package that installs debug symbols
ii  kurento-media-server                   6.14.0-0kurento1.18.04                          amd64        Kurento Media Server
ii  kurento-media-server-dbg               6.14.0-0kurento1.18.04                          amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64    1.8.1-1kurento4.18.04                           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64   1.8.1-1kurento2.18.04                           amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                1.8.1-1kurento2.18.04                           amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0-dbg:amd64            1.8.1-1kurento2.18.04                           amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                        0.1.17-0kurento1.18.04                          amd64        ICE library (shared library)
ii  libnice10-dbgsym:amd64                 0.1.17-0kurento1.18.04                          amd64        debug symbols for libnice10
ii  libsrtp0:amd64                         1.6.0-0kurento1.18.04                           amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                             0.9.2-1kurento1.18.04                           amd64        sctp-refimpl library
ii  openh264                               1.4.0-1kurento1.18.04                           amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64     1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                 0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins
ii  openwebrtc-gst-plugins-dbg             0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins
```

**Comment by j1elo** [comment] 2020-10-04 10:44
Duplicate of https://github.com/Kurento/bugtracker/issues/510

**Closed by j1elo** 2020-10-04 10:44 UTC
Labels: stability
