### ISSUE TITLE
"Hello World (WebRTC in loopback)" Remote stream not able to show

### ISSUE THREAD

**Issue by nilaydzya** [Kurento/bugtracker#437] opened 2020-02-15 19:17 UTC
Please complete the following information, where relevant.
after configurations made as shown in "https://readthedocs.org/projects/doc-kurento/downloads/pdf/stable/"

Able to see in the self image in Local Stream and unable to get it back in remote stream.

**Describe the bug**
backend shows

2020-02-15 19:13:10.892  INFO 27334 --- [nio-9443-exec-9] org.kurento.tutorial.helloworld.Handler  : [Handler::afterConnectionEstablished] New WebSocket connection, sessionId: f1500a97-bcbd-b5a1-7570-fb514fb185a0

2020-02-15 19:14:43.112  WARN 27334 --- [nio-9443-exec-5] org.kurento.tutorial.helloworld.Handler  : [Handler::afterConnectionClosed] status: CloseStatus[code=1009, reason=The decoded text message was too big for the output buffer and the endpoint does not support partial messages], sessionId: f1500a97-bcbd-b5a1-7570-fb514fb185a0

**To Reproduce**

1. Create this pipeline: '...'
2. Use these settings: '...'
3. '...'

**Expected behavior**

**Kurento Media Server**

- Kurento version: [e.g. 6.12.0, or nightly]
- Server OS: [e.g. Ubuntu 16.04 (Xenial), 18.04 (Bionic)]
- Installation method: [e.g. [apt-get](https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local), [Docker](https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker), [AWS](https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws), [build from sources](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources)]

**Application Server**

- Language: [e.g. Java, Node.js, browser JavaScript]
- Client version: [e.g. 6.12.0, or nightly]

**End-user clients**

- Device(s): [e.g. PC, Mac, Android, iPhone]
- OS(es): [e.g. Ubuntu 18.04, Windows 10, iOS8.1]
- Browser(s) [e.g. Firefox, Chrome, Safari]
- Version(s): [e.g. 79.0.3945.79]

**Version details** (please paste output of running these commands **in the machine where KMS is running**)

```
kurento-media-server -v

lsb_release -a

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Additional context**

Add any other context about the problem here. E.g. where KMS is located, where the clients are, whether you are using STUN/TURN, etc.

**Comment by coodiecool** [comment] 2020-02-20 04:36
i had the same issue that using the "Kurento Java Tutorial - Hello World".

![1582173142249](https://user-images.githubusercontent.com/59857200/74901317-78ee9180-53dd-11ea-9104-e128cb9a77e0.jpg)
![1582173167639](https://user-images.githubusercontent.com/59857200/74901323-7c821880-53dd-11ea-8719-8ab14505661c.jpg)

**Comment by nilaydzya** [comment] 2020-02-20 15:29
#########:/home/nilay/kurento-tutorial-java/kurento-hello-world# kurento-media-server -v
Kurento Media Server version: 6.13.0
Found modules:
        'core' version 6.13.0
        'elements' version 6.13.0
        'filters' version 6.13.0
##########:/home/nilay/kurento-tutorial-java/kurento-hello-world# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
root@162-241-70-149:/home/nilay/kurento-tutorial-java/kurento-hello-world# dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
ii  gir1.2-gstreamer-0.10                 0.10.36-1.5ubuntu1                                amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64              1.8.1-1kurento1.16.04                             amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64               0.1.15-1kurento3.16.04                            amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64        1.8.1-1kurento4.16.04                             amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64       1.8.1-1kurento2.16.04                             amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64       1.8.1-1kurento3.16.04                             amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64       1.8.1-1kurento1.16.04                             amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64         1.8.1-1kurento3.16.04                             amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                  1.8.1-1kurento2.16.04                             amd64        GStreamer plugins for X11 and Pango
ii  kms-core                              6.13.0-0kurento1.16.04                            amd64        Kurento Core module
ii  kms-elements                          6.13.0-0kurento1.16.04                            amd64        Kurento Elements module
ii  kms-filters                           6.13.0-0kurento1.16.04                            amd64        Kurento Filters module
ii  kms-jsonrpc                           6.13.0-0kurento1.16.04                            amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                            1.6.3-1kurento1.16.04                             amd64        Kurento jsoncpp library
ii  kurento-media-server                  6.13.0-0kurento1.16.04                            amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64   1.8.1-1kurento4.16.04                             amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64  1.8.1-1kurento2.16.04                             amd64        GStreamer libraries from the "base" set
ii  libgstreamer0.10-0:amd64              0.10.36-1.5ubuntu1                                amd64        Core GStreamer libraries and elements
ii  libgstreamer0.10-dev                  0.10.36-1.5ubuntu1                                amd64        GStreamer core development files
ii  libgstreamer1.5-0:amd64               1.8.1-1kurento2.16.04                             amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                       0.1.15-1kurento3.16.04                            amd64        ICE library (shared library)
ii  libsrtp0:amd64                        1.6.0-0kurento1.16.04                             amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                            0.9.2-1kurento1.16.04                             amd64        sctp-refimpl library
ii  openh264                              1.4.0-1kurento1.16.04                             amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64    1.8.1-1kurento4.16.04                             amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                0.10.0-1kurento1.16.04                            amd64        OpenWebRTC specific GStreamer plugins
#######:/home/nilay/kurento-tutorial-java/kurento-hello-world#

**Comment by nilaydzya** [comment] 2020-02-20 15:29
But in firefox works but not in chrome

**Comment by j1elo** [comment] 2020-02-20 16:02
Duplicate of #431

**Comment by j1elo** [comment] 2020-02-20 16:04
Kurento tutorials are version 6.13.0 but this bug was fixed in kurento-utils-js 6.13.1 so until next release of Kurento you'll have to set the dependency by hand.

**Closed by j1elo** 2020-02-20 16:04 UTC

**Comment by nilaydzya** [comment] 2020-02-20 17:59
So when we can have the amazing kurento tutorials next release ???

**Comment by j1elo** [comment] 2020-02-20 18:41
Soon around next week; anyhow, tutorials in the `master` branch should work, if not, the dependency can be changed already. Are you using java or node tutorials?

**Comment by coodiecool** [comment] 2020-02-21 03:58
> But in firefox works but not in chrome

like you said,it really works on firefox!!

**Comment by elygoncalves** [comment] 2020-05-26 01:47
Hi,

I have exactly this problem using the kurent-media-server version: 6.13.2.

Hello World
![image](https://user-images.githubusercontent.com/25504085/82852304-03f98f00-9ed9-11ea-854b-6b7e64454c1f.png)

LOG
![image](https://user-images.githubusercontent.com/25504085/82852458-6bafda00-9ed9-11ea-8754-ff1b0e35544b.png)

Can you give me more information about this problem?

Best regards,

**Comment by grimace** [comment] 2020-08-13 12:32
this doesn't work out of the box.   
git clone repo : kurento-tutorial-node.  
cd kurento-tutorial-node/hello-world
hello-world version: 6.14.1-dev
node version v8.17.0 ( also with v12.18.3 )
npm version 6.13.4
npm install
npm start
remote side just spins forever

**Comment by j1elo** [comment] 2020-08-13 16:39
Please follow the instructions from here: https://doc-kurento.readthedocs.io/en/latest/tutorials/node/tutorial-helloworld.html

**Comment by grimace** [comment] 2020-08-13 17:23
yes, my problem was there was no kurento server running - tho it seems like an appropriate error could have saved some time trying to debug it.
