### ISSUE TITLE
Invalid pts (playback timestamps) in recordings

### ISSUE THREAD

**Issue by TF-Michael** [Kurento/bugtracker#147] opened 2016-11-22 22:58 UTC
**KMS Version**:

libdc1394 error: Failed to initialize libdc1394
Version: 6.6.1
Found modules:
        Module: 'core' version '6.6.1'
        Module: 'elements' version '6.6.1'
        Module: 'filters' version '6.6.1'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.1.20160930110533.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.6.1.20160930122545.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.6.1.20160930131150.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.2.20160930094018.trusty                amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.6.1.20160930143513.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (shared library)

**Client libraries**
-Java
- Version: 6.6.0

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chromium Embedded Framework (41.0.1): Fail
- Chrome (54.0.2840.99): Fail
- Firefox: n/a
- Native: n/a

**System description:**

KMS is located on an azure server.

Clients are public customers. Half of these will always use Chromium Embedded Framework version 41.0.1 and will connect to a public customer using some version of google chrome for video calling.

We are using STUN.

**What steps will reproduce the problem?**
Seems to be random. More likely to happen with video calls going across the internet than video calls made on a local network.

**What is the expected result?**
Produce recording that can be played back.

**What happens instead?**
Recordings are produced but can only be played back if the default framerate for the recording is changed using mkvtools. Some recordings play back fine unchanged.

**Does it happen with one of the tutorials?**
We have not been able to reproduce this issue with the tutorials.

**Please provide any additional information below.**
We were told that this issue has to do with the pts in the recordings by the kurento support team. We successfully fixed one of these recordings that originally would not play back by creating a gstreamer caps filter that set a constant framerate and then afterwards adjusting the default framerate using mkvtools to the framerate set in the caps filter. After this was done we discovered that the audio was missing from this recording if played back using the kurento player endpoint. The audio played back fine with google chrome.

Here is the code for our pipeline:

this.pipeline = kurento.createMediaPipeline();
this.calleeWebRtcEP = new WebRtcEndpoint.Builder(pipeline).build();
this.callerWebRtcEP = new WebRtcEndpoint.Builder(pipeline).build();
recorderCaller = new RecorderEndpoint.Builder(pipeline, RECORDING_PATH).build();
recorderCallee = new RecorderEndpoint.Builder(pipeline, RECORDING_PATH).build();
calleeWebRtcEP.connect(recorderCallee);
callerWebRtcEP.connect(recorderCaller);
calleeWebRtcEP.setMaxVideoSendBandwidth(100);
calleeWebRtcEP.setMaxVideoRecvBandwidth(100);		callerWebRtcEP.setMaxVideoSendBandwidth(100);
callerWebRtcEP.setMaxVideoRecvBandwidth(100);

calleeWebRtcEP.addMediaStateChangedListener();
callerWebRtcEP.addMediaStateChangedListener();	

when the media state changed event has been triggered from both webrtc endpoints we call the record function. The recording is stopped by call release() on the recorder endpoints.

**Comment by TF-Michael** [comment] 2016-12-07 19:38
For more information please read:
https://groups.google.com/d/msgid/kurento/2da6226a-06c3-44a8-a813-4cfdc818a7ce%40googlegroups.com

**Comment by TF-Michael** [comment] 2016-12-07 22:58
*** caller sdp answer ***

v=0
o=- 3690139428 3690139428 IN IP4 0.0.0.0
s=Kurento Media Server
c=IN IP4 0.0.0.0
t=0 0
a=msid-semantic: WMS V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk
a=group:BUNDLE audio video
m=audio 1 RTP/SAVPF 111 0
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:audio
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=setup:active
a=sendrecv
a=rtcp-mux
a=fmtp:111 minptime=10; useinbandfec=1
a=maxptime:60
a=ssrc:3993664178 cname:user267466160@host-8d65244e
a=ice-ufrag:NbEE
a=ice-pwd:MuCPFn/iCKqlvJyn62qgUK
a=fingerprint:sha-256 B1:E7:F5:1F:6A:FD:FF:40:7F:09:87:6B:49:89:9F:44:C0:9A:C2:23:ED:EA:5D:C5:FF:5E:AB:C6:9A:C1:5F:F2
m=video 1 RTP/SAVPF 100
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:video
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=setup:active
a=sendrecv
a=rtcp-mux
a=ssrc:4197122403 cname:user267466160@host-8d65244e
a=ice-ufrag:NbEE
a=ice-pwd:MuCPFn/iCKqlvJyn62qgUK
a=fingerprint:sha-256 B1:E7:F5:1F:6A:FD:FF:40:7F:09:87:6B:49:89:9F:44:C0:9A:C2:23:ED:EA:5D:C5:FF:5E:AB:C6:9A:C1:5F:F2

**Comment by TF-Michael** [comment] 2016-12-07 22:58
v=0
o=- 1415294986360909381 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk
m=audio 9 RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:s5jvIYI4UKvbVyAE
a=ice-pwd:Rift3Vbdb1FrMKzNYkGtpxoe
a=fingerprint:sha-256 66:32:C3:9B:09:ED:21:8E:AD:A6:92:3A:55:66:93:E1:4E:0F:78:C8:2F:BC:7F:DD:FF:5C:C8:8E:35:0C:65:99
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:838389582 cname:V7IckY6+9oJsBhhB
a=ssrc:838389582 msid:V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk 6cead214-8796-43d0-93eb-01b81045bc96
a=ssrc:838389582 mslabel:V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk
a=ssrc:838389582 label:6cead214-8796-43d0-93eb-01b81045bc96
m=video 9 RTP/SAVPF 100 116 117 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:s5jvIYI4UKvbVyAE
a=ice-pwd:Rift3Vbdb1FrMKzNYkGtpxoe
a=fingerprint:sha-256 66:32:C3:9B:09:ED:21:8E:AD:A6:92:3A:55:66:93:E1:4E:0F:78:C8:2F:BC:7F:DD:FF:5C:C8:8E:35:0C:65:99
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 628303494 527080205
a=ssrc:628303494 cname:V7IckY6+9oJsBhhB
a=ssrc:628303494 msid:V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk 8f4282cd-0db9-46f4-864e-5ba436503d19
a=ssrc:628303494 mslabel:V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk
a=ssrc:628303494 label:8f4282cd-0db9-46f4-864e-5ba436503d19
a=ssrc:527080205 cname:V7IckY6+9oJsBhhB
a=ssrc:527080205 msid:V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk 8f4282cd-0db9-46f4-864e-5ba436503d19
a=ssrc:527080205 mslabel:V1JVlMH8am2L5vJKrJQjyIpanj04WtBuvctk
a=ssrc:527080205 label:8f4282cd-0db9-46f4-864e-5ba436503d19

**Comment by TF-Michael** [comment] 2016-12-07 22:59
*** callee sdp offer ***

v=0
o=- 7814014578981791764 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:g3kz
a=ice-pwd:LSENnN6kUE6Q1Hjt4rAB1Bni
a=fingerprint:sha-256 93:A5:A1:9A:44:43:3D:D5:AA:E5:CF:FC:F9:E3:7A:03:28:BA:01:89:12:58:5A:D7:7E:3B:23:7B:A0:46:9A:E1
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=ssrc:1606971272 cname:0dObzmm8nUb0cZsH
a=ssrc:1606971272 msid:3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK b7c5c31c-8a32-4183-b99b-d4ea0862861b
a=ssrc:1606971272 mslabel:3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK
a=ssrc:1606971272 label:b7c5c31c-8a32-4183-b99b-d4ea0862861b
m=video 9 UDP/TLS/RTP/SAVPF 100 101 107 116 117 96 97 99 98
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:g3kz
a=ice-pwd:LSENnN6kUE6Q1Hjt4rAB1Bni
a=fingerprint:sha-256 93:A5:A1:9A:44:43:3D:D5:AA:E5:CF:FC:F9:E3:7A:03:28:BA:01:89:12:58:5A:D7:7E:3B:23:7B:A0:46:9A:E1
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtpmap:101 VP9/90000
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 transport-cc
a=rtpmap:107 H264/90000
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:107 transport-cc
a=fmtp:107 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=107
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=116
a=ssrc-group:FID 3384223984 421259480
a=ssrc:3384223984 cname:0dObzmm8nUb0cZsH
a=ssrc:3384223984 msid:3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK 44cbf71a-4471-4794-9b24-1a37f64c7099
a=ssrc:3384223984 mslabel:3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK
a=ssrc:3384223984 label:44cbf71a-4471-4794-9b24-1a37f64c7099
a=ssrc:421259480 cname:0dObzmm8nUb0cZsH
a=ssrc:421259480 msid:3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK 44cbf71a-4471-4794-9b24-1a37f64c7099
a=ssrc:421259480 mslabel:3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK
a=ssrc:421259480 label:44cbf71a-4471-4794-9b24-1a37f64c7099

**Comment by TF-Michael** [comment] 2016-12-07 22:59
*** callee sdp answer ***

v=0
o=- 3690139428 3690139428 IN IP4 0.0.0.0
s=Kurento Media Server
c=IN IP4 0.0.0.0
t=0 0
a=msid-semantic: WMS 3deJZHtmEsNEvvksmIruKwnEbRpDPjFTvzsK
a=group:BUNDLE audio video
m=audio 1 UDP/TLS/RTP/SAVPF 111 0
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:audio
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=setup:active
a=sendrecv
a=rtcp-mux
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:3746592394 cname:user1567414118@host-f49e8b50
a=ice-ufrag:ByDa
a=ice-pwd:kX95WVGdykdNy3HaZAndpG
a=fingerprint:sha-256 B1:E7:F5:1F:6A:FD:FF:40:7F:09:87:6B:49:89:9F:44:C0:9A:C2:23:ED:EA:5D:C5:FF:5E:AB:C6:9A:C1:5F:F2
m=video 1 UDP/TLS/RTP/SAVPF 100
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:video
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=setup:active
a=sendrecv
a=rtcp-mux
a=ssrc:2632849843 cname:user1567414118@host-f49e8b50
a=ice-ufrag:ByDa
a=ice-pwd:kX95WVGdykdNy3HaZAndpG
a=fingerprint:sha-256 B1:E7:F5:1F:6A:FD:FF:40:7F:09:87:6B:49:89:9F:44:C0:9A:C2:23:ED:EA:5D:C5:FF:5E:AB:C6:9A:C1:5F:F2

**Comment by TF-Michael** [comment] 2016-12-07 23:00
Records VP8 to a webm file.

**Comment by stonyz** [comment] 2018-07-05 01:58
Did you solve the issue? I have the same problem.. the recorded file can replay, but only have audio, doesn't have video. after check via ffmpeg, the DTS is very big(not start from 0)

**Comment by Napoleon-Black** [comment] 2019-02-07 09:27
I have the same issue using Kurento 6.9.0.
Problem reproduced if user has problems with internet connection .
Maybe it's because WEBM video was recorded in dynamic dimensions?

![1549531387126](https://user-images.githubusercontent.com/17879113/52401827-5556f280-2acb-11e9-997e-55eda788e289.jpg)

**Comment by j1elo** [comment] 2020-06-25 19:17
Is this still an issue? If so, please comment. WEBM or MKV recording should work best for videos that chage resolution.

**Comment by Napoleon-Black** [comment] 2020-06-30 06:59
Yes, this issue still reproduced on Kurento Media Server 6.13.0
But it reproduced only if I use RecorderEndpoint, if I connect RecorderEndpoint through Composite element all works fine.

**Comment by j1elo** [comment] 2020-06-30 10:38
There is a known bug which affects the RecorderEndpoint when the source stream gets interrupted. Could you read the following issue analysis (attached file) and comment on whether this is the case or not?

[RecorderEndpoint-timestamps.txt](https://github.com/Kurento/bugtracker/files/4851186/RecorderEndpoint-timestamps.txt)

**Comment by j1elo** [comment] 2020-06-30 10:40
Also it's worth to check and see if this post-processing helps with the wrong timestamp videos (for MP4 recordings):

      ffmpeg -i input.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts temp.ts
      ffmpeg -i temp.ts -c copy -video_track_timescale 90000 -movflags faststart -f mp4 -threads 1 output.mp4
      rm temp.ts

**Comment by j1elo** [comment] 2023-01-18 15:51
I think this should have been fixed by https://github.com/Kurento/kms-core/pull/29, https://github.com/Kurento/kms-core/commit/d132cb7c2d1bfcb00c12829367c144e058f35815

**Closed by j1elo** 2023-01-18 15:51 UTC
Labels: bug
