### ISSUE TITLE
Exception encountered during context initializa tion - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException

### ISSUE THREAD

**Issue by mjkim103301** [Kurento/bugtracker#607] opened 2021-08-04 15:37 UTC
## Prerequisites

These are MANDATORY, otherwise the issue will be automatically closed.

* [x] I agree to fill this issue template.
* [] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

The kurento-tutorial-java/kurento-magic-mirror example was previously running well, but suddenly the following error occurs:
```
2021-08-05 00:20:06.151 ERROR 8296 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketHandlerMapping' defined in org.springframework.web
.socket.config.annotation.DelegatingWebSocketConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.b
eans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'webSocketHandlerMapping' t
hrew exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'handler': Unsa
tisfied dependency expressed through field 'kurento'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating b
ean with name 'kurentoClient' defined in org.kurento.tutorial.magicmirror.MagicMirrorApp: Bean instantiation via factory method failed; nested exce
ption is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.kurento.client.KurentoClient]: Factory method 'kurentoCli
ent' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-5.2.10.RELEASE.ja
r:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:483) ~[spring-beans
-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFa
ctory.java:1336) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:
1176) ~[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~
[spring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[s
pring-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.10.REL
EASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-bean
s-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.10.RELEASE.jar:
5.2.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.10.RELEASE.jar:5.
2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spr
ing-beans-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[sp
ring-context-5.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.10.RELE
ASE.jar:5.2.10.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[s
pring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
        at org.kurento.tutorial.magicmirror.MagicMirrorApp.main(MagicMirrorApp.java:64) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory me
thod 'webSocketHandlerMapping' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creatin
g bean with name 'handler': Unsatisfied dependency expressed through field 'kurento'; nested exception is org.springframework.beans.factory.BeanCre
ationException: Error creating bean with name 'kurentoClient' defined in org.kurento.tutorial.magicmirror.MagicMirrorApp: Bean instantiation via fa
ctory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.kurento.client.KurentoCli
ent]: Factory method 'kurentoClient' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to K
MS
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5
.2.10.RELEASE.jar:5.2.10.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-5.2.10.RELEASE.ja
r:5.2.10.RELEASE]
        ... 20 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'handler': Unsatisfied dependency expres
sed through field 'kurento'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kurentoCli
ent' defined in org.kurento.tutorial.magicmirror.MagicMirrorApp: Bean instantiation via factory method failed; nested exception is org.springframew
ork.beans.BeanInstantiationException: Failed to instantiate [org.kurento.client.KurentoClient]: Factory method 'kurentoClient' threw exception; nes
ted exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
```

## How to reproduce?

I just ran a kurento-magic-mirror example with the following command:
mvn -U clean spring-boot:run -Dspring-boot.run.jvmArguments="-Dkms.url=ws://{aws public ip}
:8888/kurento"

## Expected & current behavior

https://localhost:8443 Connection was successful. But even though there was no code change this evening, I suddenly can't access it.

### About Kurento Media Server

* Kurento version:  6.16.0
* Server OS:          Ubuntu 18.04
* Installation method:
    
  - [x] [apt-get]
  - [x] [Docker]
  - [x] [AWS CloudFormation]
  - [] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### About your Application Server

* Programming Language:  Java
* Kurento Client version:     6.16.0

### About end-user clients

* Device(s):    PC
* OS(es):        Windows10
* Browser(s):  Chrome

### Run these commands

```
cat /etc/lsb-release
```

```
kurento-media-server --version
```

```
dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment] 2021-08-11 08:47
The exception message says `org.kurento.commons.exception.KurentoException: Exception connecting to KMS`, so I'm inclined to think this is a connectivity problem between your Java process and the Kurento Media Server process. The {aws public ip} probably doesn't have the port 8888 reachable from where Java is running.

As a quick test, I ran:

```
# Terminal 1
docker pull kurento/kurento-media-server:latest
docker run --rm --network host kurento/kurento-media-server:latest
```

```
# Terminal 2
cd kurento-tutorial-java/kurento-magic-mirror/
mvn clean spring-boot:run -Dspring-boot.run.jvmArguments="-Dkms.url=ws://localhost:8888/kurento"
```

And it all worked fine. So I'm closing this as not a bug.

**Closed by j1elo** 2021-08-11 08:47 UTC
Labels: not-a-bug
