### ISSUE TITLE
When support VP9 ?

### ISSUE THREAD

**Issue by zhangalex** [Kurento/bugtracker#239] opened 2018-03-27 18:37 UTC
It is likely that KMS doesn't support VP9 for now. Do you have any plan on VP9 ?

**Comment by LeoColomb** [comment] 2018-03-30 12:41
Or even the new AV1 (the successor of VP9). 👍 
These supports need at least a Gstreamer update (which seems to be [on the roadmap](http://www.kurento.org/blog/kurento-67-moving-forward) 🙌).

**Comment by micaelgallego** [comment] 2018-03-31 10:20
One of our main priorities is update GStreamer to the latest version (1.14)
released some weeks ago. Also we use other libraries that we plan to update
also.

When we update all those libraries, we will start testing new codecs like
VP9 and AV1.

**Comment by LeoColomb** [comment] 2018-04-04 08:01
@zhangalex Any reason you are closing the issue? 🙂

**Comment by micaelgallego** [comment] 2018-04-04 09:14
The question has been answered ;)

But we can maintain it open to track progress... at least until better issue is created for that.

**Comment by zhangalex** [comment] 2018-04-08 15:30
@micaelgallego  Yes, it has been answered. haha.

**Comment by micaelgallego** [comment] 2018-04-11 07:29
I can't tell you when VP9 support will be available. It depends on how much time we spend updating GStreamer, testing VP9 support on that, testing compatibility with Chrome, etc. 

Just for curiosity, why do you want VP9 support? Only for reducing bandwidth usage?

**Comment by zhangalex** [comment] 2018-04-17 04:05
@micaelgallego   Yes, because our project is running in a private network (it cannot access internet), and the bandwidth in some area is not stable, so we need reduce bandwidth.

**Comment by zhangalex** [comment] 2018-07-06 06:08
Is there any progress on this?

**Comment by Ezanor** [comment] 2019-02-22 15:53
@micaelgallego 

Any news on that ?

**Comment by broderix** [comment] 2019-05-20 21:05
up

**Comment by micaelgallego** [comment] 2019-05-21 07:11
We are in the process to update Kurento Media Server to GStreamer 1.14. We will take a look to VP9 support after that

**Comment by j1elo** [comment] 2020-04-30 16:17
Closing because this is not a bug. Also, the update to GStreamer 1.14 got stalled for some time although 2020 seems like it will see the light.

In any case, top priority to Kurento is keep compatibility with Chrome and Firefox, that is already enough work for our small team, and it doesn't make much sense working to support AV1 if Chrome doesn't support it either...

VP9 will be considered as a "nice to have" feature when porting to GStreamer 1.14 (and possibly 1.16) is finally done.

**Closed by j1elo** 2020-04-30 16:17 UTC

**Comment by alfredonodo** [comment] 2021-04-11 08:34
Hi,
I wonder to know if now kurento supports VP9 video codec.
Thank you

**Comment by kfbixc** [comment] 2021-04-16 15:56
any progress?

**Comment by robregonm** [comment] 2021-04-16 21:10
I think that it's a better idea to focus on **AV1**, since it is supported by Safari, Chrome and Firefox, and compression rates are much better than VP9.
Notice that VP9 is not currently supported by Safari

**Comment by alfredonodo** [comment] 2021-04-17 07:20
@robregonm safari supports VP9 codec on WebRTC since iOS14 https://webkit.org/blog/10929/release-notes-for-safari-technology-preview-110/.
The main problem with AV1 and with VP9 too, is the missing hardware encoding and decoding capabilities (VP9 it is a lot ahead on this https://en.wikipedia.org/wiki/VP9#Hardware_device_support).

**Comment by pachainti** [comment] 2021-04-25 15:39
@j1elo any news?

**Comment by j1elo** [comment] 2021-05-10 17:53
Kurento will not support VP9 or AV1 in the foreseeable future; we're working to add this directly to OpenVidu; if there is enough commercial interest, we'd possibly fund progress on upgrading Kurento's GStreamer fork, which in turn unblocks the addition of newer codecs.

**Comment by themightyoarfish** [comment] 2023-04-27 07:02
I'm assuming this won't happen? Bummer.
What specifically makes this difficult? ffmpeg and gstreamer both support vp9 encoding and payloading for RTP for instance.
