### ISSUE TITLE
AWS Cloud Formation template: stack creation failure

### ISSUE THREAD

**Issue by pmontrasio** [Kurento/bugtracker#263] opened 2018-06-25 07:13 UTC
1. Start the installation on AWS with the template https://s3-eu-west-1.amazonaws.com/aws.kurento.org/KMS-Coturn-cfn.yaml as specified by http://doc-kurento.readthedocs.io/en/stable/user/installation.html#amazon-web-services
Click Next

2. On the second page of the wizard: InstanceType, select `m1.large` (see #262 for the reason why the default `t2.large` doesn't work); Specify Details, type Kurento as stack name; Parameters: use the defaults but select a KeyName and change the TurnPassword. Click Next.

3. On the third page of the wizard: leave Tags empty; leave Permissions empty; leave Rollback Triggers empty; do not set any Advanced option. Click Next.

4. Click Create.

**What is the expected result?**

The creation of the stack.

**What happens instead?**

The creation process fails. See the message at timestamp 09:02:38 in the log below.

**Does it happen with one of the tutorials?**

Yes, http://doc-kurento.readthedocs.io/en/stable/user/installation.html

**Please provide any additional information below.**

```
2018-06-25 | Status | Type | Logical ID | Status Reason
09:03:25 UTC+0200 ROLLBACK_COMPLETE AWS::CloudFormation::Stack Kurento         
09:03:24 UTC+0200 DELETE_COMPLETE AWS::EC2::SecurityGroup KurentoMediaServerSecurityGroup         
09:03:23 UTC+0200 DELETE_IN_PROGRESS AWS::EC2::SecurityGroup KurentoMediaServerSecurityGroup         
09:03:22 UTC+0200 DELETE_COMPLETE AWS::EC2::Instance KurentoMediaServer         
09:02:51 UTC+0200 DELETE_COMPLETE AWS::CloudFormation::WaitCondition WaitCondition         
09:02:51 UTC+0200 DELETE_IN_PROGRESS AWS::CloudFormation::WaitCondition WaitCondition         
09:02:51 UTC+0200 DELETE_IN_PROGRESS AWS::EC2::Instance KurentoMediaServer         
09:02:39 UTC+0200 ROLLBACK_IN_PROGRESS AWS::CloudFormation::Stack Kurento  The following resource(s) failed to create: [WaitCondition]. . Rollback requested by user.       
09:02:38 UTC+0200 CREATE_FAILED AWS::CloudFormation::WaitCondition WaitCondition  Failed to receive 1 resource signal(s) within the specified duration       
08:58:15 UTC+0200 CREATE_COMPLETE AWS::EC2::Instance KurentoMediaServer         
08:57:42 UTC+0200 CREATE_IN_PROGRESS AWS::EC2::Instance KurentoMediaServer  Resource creation Initiated       
08:57:41 UTC+0200 CREATE_IN_PROGRESS AWS::EC2::Instance KurentoMediaServer         
08:57:39 UTC+0200 CREATE_COMPLETE AWS::EC2::SecurityGroup KurentoMediaServerSecurityGroup         
08:57:38 UTC+0200 CREATE_IN_PROGRESS AWS::EC2::SecurityGroup KurentoMediaServerSecurityGroup  Resource creation Initiated       
08:57:37 UTC+0200 CREATE_IN_PROGRESS AWS::EC2::SecurityGroup KurentoMediaServerSecurityGroup         
08:57:37 UTC+0200 CREATE_IN_PROGRESS AWS::CloudFormation::WaitCondition WaitCondition  Resource creation Initiated       
08:57:37 UTC+0200 CREATE_IN_PROGRESS AWS::CloudFormation::WaitCondition WaitCondition         
08:57:34 UTC+0200 CREATE_IN_PROGRESS AWS::CloudFormation::Stack Kurento  User Initiated 
```

**Comment by neilyoung** [comment] 2018-06-25 07:34
Confirmed. The installation via AWS template is not working

**Comment by nordri** [comment] 2018-06-25 07:48
Hello,
I'm sorry to hear that. Actually, I'm trying to reproduce the problem but I can't.
I can deploy the stack with both flavors.
Is the problem that you wanna deploy without VPC?
As far as I know you need a VPC... Actually is the first thing you do when you start with AWS...
Take a look to this doc: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-vpc.html
LMK if i can help you in something else.
Cheers!

**Comment by neilyoung** [comment] 2018-06-25 07:51
@nordri Sure, I don't use a VPC. Where is it declared as requirement for Kurento?

**Comment by neilyoung** [comment] 2018-06-25 07:59
@nordri But while checking my AWS console I see that there is a default VPC

**Comment by neilyoung** [comment] 2018-06-25 08:06
@nordri I actually seem to have a different problem. The status changes from CREATE_IN_PROGRESS to ROLLBACK_COMPLETE in 30 secs

<img width="1802" alt="cloudformation_management_console" src="https://user-images.githubusercontent.com/731020/41837998-69946562-785f-11e8-841f-f4584a3a150d.png">

**Comment by neilyoung** [comment] 2018-06-25 08:18
@nordri Uhm... Seems to be my bad. I was not creating an SSH keypair in preparations

**Comment by nordri** [comment] 2018-06-25 08:20
@neilyoung OK!
This issue make us realized our documentation isn't complete enough, we will give a review to avoid this things in the future.

**Comment by neilyoung** [comment] 2018-06-25 08:22
@nordri Yep. At least an SSH keypair needs to be generated beforehand and configured in the template. Stack is up. Not sure if it is running yet, will try some examples now and let you know

**Comment by neilyoung** [comment] 2018-06-25 08:41
@nordri OK, the Kurento server @AWS is running. But there is the same problem as with the local installations: There is only one of the many JS examples running: The loopback. Magic-Mirror and others are not working. The last vital sign in the Chrome developer console is, that I receive a lot of "remote ICE candidates". The last trace is "Set overlay image". The overlay image is available on a public server. But then nothing else happens. The right window in the browser just contains a spinning wheel.

I have the same results with all examples (except loopback) in a local installation scenario.

One more thing: The AWS instance seems to be available via HTTP only, right? I can telnet it at port 8888 but not at port 8433.

**Comment by nordri** [comment] 2018-06-26 07:14
Hello @neilyoung 
Yeah, Kurento is only exposed on 8888/TCP
You can check it's running:
`curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: INSTANCE_IP:8888" -H "Origin: INSTANCE_IP" http://INSTANCE_IP:8888/kurento`
Raplace INSTANCE_IP for you instance public IP.
You should see something like this
```
HTTP/1.1 500 Internal Server Error
Server: WebSocket++/0.5.1
```
Don't worry about the 500 error, that is because we didn't use the web socket properly. But it shows how KMS is up and running.

**Comment by micaelgallego** [comment] 2018-06-26 07:20
@neilyoung we are aware that something is wrong with the tutorials. We are working on them.

But it is a problem with tutorials, not with Kurento Media Server itself.

**Comment by nordri** [comment] 2018-06-26 09:35
On the other hand, we've updated the doc explaining how to use AWS CloudFormation templates. You can check it out here: 
https://doc-kurento.readthedocs.io/en/latest/user/installation.html
Saying that, we close the issue.

**Closed by nordri** 2018-06-26 09:35 UTC

**Comment by neilyoung** [comment] 2018-06-26 10:43
@micaelgallego Do you mean, there is just a documentation issue? None of the tutorials is working, except loopback, IMHO. It is pretty unclear, where the error is. Let me know, if I can help

**Comment by nordri** [comment] 2018-06-26 13:09
@neilyoung Kurento team is very small now and we all are very busy with other stuff of the project. Which means that we know there's something wrong with the tutorials but we are focus on Media Server and it works fine.
We sorry for the inconvenience and for sure, we'll make the tutorials work again as soon as possible.

**Comment by neilyoung** [comment] 2018-06-26 14:17
@nordri I totally understand that, but I also have my deadlines
