### ISSUE TITLE
KMS 6.13.0 segmentation fault crash

### ISSUE THREAD

**Issue by jbabob** [Kurento/bugtracker#531] opened 2020-09-23 17:36 UTC
## Prerequisites

* [x] I agree to fill this issue template.
* [x] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description

KMS service went from active (running) to active (exited) without notice. The service had been running for a couple of weeks the first time it happened and about a day the second time. The error logs contained this:
```
2020-08-06T17:48:28+00:00 -- New execution
Segmentation fault (thread 139943108368128, pid 1331)
Stack trace:


2020-09-22T14:59:25+00:00 -- New execution
Segmentation fault (thread 140584901490432, pid 15185)
Stack trace:


```
The stack trace is empty for both entries. Nothing in the Kurento log file seems to indicate an error.

The logs from KurentoClient look like this:
```
2020-09-23 09:08:55.443  WARN 8 --- [tLoopGroup-46-1] o.k.j.c.JsonRpcClientNettyWebSocket      : [KurentoClient]  Exception caught in Netty websocket handler

java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.IOUtil.read(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.IOUtil.read(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:na]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-buffer-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2020-09-23 09:08:55.443  INFO 8 --- [tLoopGroup-46-1] o.k.j.c.JsonRpcClientNettyWebSocket      : [KurentoClient]  channel closed
2020-09-23 09:08:55.444  WARN 8 --- [tLoopGroup-46-1] o.k.j.c.AbstractJsonRpcClientWebSocket   : [KurentoClient]  Exception sending close message. org.kurento.jsonrpc.JsonRpcErrorException:Connection with server have been closed
2020-09-23 09:08:55.444 ERROR 8 --- [tExec-e48-t1628] o.k.c.i.c.RemoteObjectInvocationHandler  : Exception while processing event 'ConnectionStateChangedEvent' with params '{timestampMillis=1600852135306, oldState=DISCONNECTED, source=805a5123-5939-4de5-a134-89d37fef6fc7_kurento.MediaPipeline/22c13473-464b-42fb-8896-83c4e148f695_kurento.WebRtcEndpoint, type=ConnectionStateChanged, newState=CONNECTED, tags=[], timestamp=1600852135}'

org.kurento.client.internal.server.KurentoServerException: Connection with server have been closed (Code:0, Type:null, Data: null)
```

And then any subsequent attempt to connect with KurentoClient will result in these logs:
```
2020-09-23 13:05:38.504  INFO 8 --- [nio-8080-exec-2] o.k.j.c.JsonRpcClientNettyWebSocket      : [KurentoClient]  Connecting native client
2020-09-23 13:05:38.504  INFO 8 --- [nio-8080-exec-2] o.k.j.c.JsonRpcClientNettyWebSocket      : [KurentoClient]  Creating new NioEventLoopGroup
2020-09-23 13:05:38.505  INFO 8 --- [tLoopGroup-57-1] o.k.j.c.JsonRpcClientNettyWebSocket      : [KurentoClient]  Initiating new Netty channel. Will create new handler too!
2020-09-23 13:05:38.507  WARN 8 --- [nio-8080-exec-2] o.k.j.c.JsonRpcClientNettyWebSocket      : [KurentoClient]  Trying to close a JsonRpcClientNettyWebSocket with channel == null
2020-09-23 13:05:38.508  WARN 8 --- [beatExec-e60-t0] o.kurento.jsonrpc.client.JsonRpcClient   : [KurentoClient]  Error sending heartbeat to server. Exception: InterruptedException while trying to acquire lock
2020-09-23 13:05:38.508  WARN 8 --- [beatExec-e60-t0] o.kurento.jsonrpc.client.JsonRpcClient   : [KurentoClient]  Stopping heartbeat and closing client: failure during heartbeat mechanism
2020-09-23 13:05:38.508 ERROR 8 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS] with root cause

java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[na:na]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

## Context

We're streaming a single video file to a target with a WebRtcEndpoint and PlayerEndpoint. Multiple streams can happen at once.

## How to reproduce?

Seems to happen randomly.

## Expected & current behavior

Kurento Service won't shut down without notice. It could attempt to restart itself.

### INFO about Kurento Media Server

* Kurento version: 6.13.0
* Server OS: Ubuntu 18.04
* Installation method:
  - [x] [apt-get]
  - [] [Docker]
  - [] [AWS CloudFormation]
  - [] [Built from sources]

[apt-get]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local
[Docker]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-docker
[AWS CloudFormation]: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-aws
[Built from sources]: https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#dev-sources

### INFO about your Application Server

* Language: Java Sprint Boot                
* Kurento Client version: 6.13.0   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

## INFO about your environment

Using WebRtcEndpoint and PlayerEndpoint
Using our own STUN server

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by j1elo** [comment] 2020-09-25 08:10
Duplicate of #111

**Comment by j1elo** [comment] 2020-09-25 08:12
This was fixed with https://github.com/Kurento/kms-core/commit/2f144b59765822ec49f72a0a2a95b0011da2774c (Kurento 6.14), solution is to upgrade to latest version: https://doc-kurento.readthedocs.io/en/latest/user/installation.html#local-upgrade

**Closed by j1elo** 2020-09-25 08:12 UTC
