### ISSUE TITLE
I Can't see remote video, docker kurento/kurento-media-server image

### ISSUE THREAD

**Issue by jlameiro87** [Kurento/bugtracker#196] opened 2017-09-28 20:23 UTC
I'm using kurento with docker, i'm pull kurento/kurento-media-server, when I run examples (I'm try with node and java examples) I never see remote video, when I using Chrome I allways see local video and see the logs that "appears" to show server responses:
![sin titulo](https://user-images.githubusercontent.com/31218194/30988615-e0a930f4-a468-11e7-8793-b840dd2c2f08.png)
When I try with firefox, i can't see local video neither remote video and got this warning in the console:
TURN server is not configured, I configure TURN server according to documentation and restart kurento service but still have the save warning in the console. 
I'm running the examples in other PC that Kurento Media Server is running.
Has anyone this error and how can I resolve it?

**Comment by rgordeev** [comment] 2017-10-13 12:22
Hello! Could you please show your Dockerfile and the command you use to run a container? I suspect you didn't map ports properly.
You should add something like 
```
EXPOSE 8888 
EXPOSE 49152-65535/udp 
EXPOSE 8433 
EXPOSE 3478
```
And then run your container as following:
```
docker run -p 8888:8888 -p 8433:8433 -p 3478:3478 -p 3478:3478/udp -p 49152-65535:49152-65535/udp <your-docker-image-name-here>
```

**Comment by ngocdiep** [comment] 2018-06-13 07:37
Hello! Is there anybody fixed this issue?

**Comment by hgsongAtWanted** [comment] 2019-11-25 05:09
(Too Late but.. )Actually **rgordeev**'s solution is working but  "49152-65535:49152-65535/udp" port is conflicted while running docker. So, you should limit udp port in turnserver.(min-port/max-port). In my case, I set min-port 50000 and max-port 50010 in my turnserver. 
And
docker run -p 8888:8888 -p 8433:8433 -p 3478:3478 -p 3478:3478/udp -p 50000-50010:50000-50010/udp <your-docker-image-name-here>

**Comment by anil1712** [comment] 2020-01-14 06:08
It is happening to me also, the loader keep spinning. I tried the above command but getting the same.
Is anyone got any solution for this?

**Comment by RossSong** [comment] 2020-01-14 07:02
Maybe.. plz check firewall setting in client computer.(especially in windows).

**Comment by j1elo** [comment] 2020-01-29 11:00
You might also simply run with host network, it makes network admin easier to work with Kurento.

Anyways, if you need a large port range (for lots of WebRTC sessions at the same time), opening up a lot of ports in Docker seems to have problems. I read this while studying about using Docker in Kubernetes, it also applies to non-Kubernetes setups: https://serverfault.com/questions/954715/webrtc-mcu-sfu-inside-kubernetes-port-ranges/955635#955635

**Comment by j1elo** [comment] 2020-01-29 11:02
I'm closing this one because it is not a bug in Kurento (please reopen if you think otherwise, with more info about what you think is a bug).

For questions about how to run Kurento and help to configure Docker, please ask in the [open-source community forums](https://groups.google.com/forum/#!forum/kurento)

**Closed by j1elo** 2020-01-29 11:02 UTC

**Comment by jjunohj** [comment] 2023-04-29 15:46
To RossSong
I'm getting this issue as same as you.
can you tell me your KMS docker port range and your TURN server port range??
I'm using coturn right now.
