### ISSUE TITLE
Permissive License for tutorial code

### ISSUE THREAD

**Issue by mrloop** [Kurento/bugtracker#39] opened 2016-03-02 10:43 UTC
License tutorial code under more permissive license e.g. BSD.

I wonder how many people are unintentionally breaking LGPL by not releasing their application code if they've used the tutorial code as a starting point. Was the decision to licence the tutorial code as LGPL taken because the main body of work is licensed under LGPL and it happened by default?

**Comment by jcaden** [comment] 2016-03-02 11:11
You are right, modify a tutorial, a demo or a library, licensed under LGPL license, and not releasing code changes when distributing it is clearly a LGPL violation.

Tutorials and demos are correctly licensed under LGPL, because they are just this, tutorials. They are not intended to be a boilerplate to develop an application.

It seems that a lot of people is taking tutorials and demos as applications when they aren't. The purpose of this demos is to teach how to use the mediaserver, but they can contain many problems when you use them as  applications. Developers should create their own applications, it is OK to get ideas and concepts from tutorials, this is its purpose, but not take them as an application or starting point for one, specially when you don't want to license it under LGPL.

PS: Closing because it's not a bug, this kind of questions should be discusses in the mailing list: https://groups.google.com/forum/#!forum/kurento

**Closed by jcaden** 2016-03-02 11:11 UTC
