### ISSUE TITLE
Why kms-core checks for gstreamer-check library presence?

### ISSUE THREAD

**Issue by kirushyk** [Kurento/bugtracker#69] opened 2016-05-10 23:59 UTC
In CMakeLists.txt there is generic_find for gstreamer-check-1.5.
But it seems not to be used. Or am I wrong?

**Comment by dfernandezlop** [comment] 2016-05-11 07:53
Hi,

We use gstreamer-check in our tests [1].

This is not a bug, for asking questions please use the kurento public list [2].

I'm closing this thread.

[1] https://github.com/Kurento/kms-core/blob/master/tests/check/element/CMakeLists.txt
[2] https://groups.google.com/forum/#!forum/kurento

**Closed by dfernandezlop** 2016-05-11 07:53 UTC

**Comment by kirushyk** [comment] 2016-05-11 09:24
Sorry!

Thank you for clarification.
