### ISSUE TITLE
Kurento Media Server can not support iceRestart ?

### ISSUE THREAD

**Issue by sshsun1990** [Kurento/bugtracker#452] opened 2020-03-26 06:06 UTC
KMS Team have plan support iceRestart?

**Comment by j1elo** [comment] 2020-03-26 12:57
No, and it's not in the short term roadmap.
For other questions about Kurento please use the [community forum](https://groups.google.com/forum/#!forum/kurento)

Closing this, as it is not a bug.

**Closed by j1elo** 2020-03-26 12:57 UTC
Labels: not-a-bug

**Comment by hdev72** [comment] 2022-04-29 21:28
> No, and it's not in the short term roadmap. For other questions about Kurento please use the [community forum](https://groups.google.com/forum/#!forum/kurento)
> 
> Closing this, as it is not a bug.

hello dear admin,
 i think its a bug because when user has unstable network we need to reconnect , now when kurento doesn't has this feature how can we reconnect user to room normally? we should restart all process of offer answers between all participants?
