### ISSUE TITLE
KMS server 6.7 on ubuntu 16.04 crashed with "Segmentation fault"

### ISSUE THREAD

**Issue by ktincheva** [Kurento/bugtracker#208] opened 2017-11-02 09:23 UTC
I cannot to reproduce the crach bacause it happends sometimes.
I use KMS for meny-to-meny video support, but some times KMS crashes whi this error:

Nov 01 16:55:56 kurento kurento.sh[2577]: 0:40:11.307340887  2579 0x7f9e78016800 ERROR        rtpsynchronizer kmsrtpsynchronizer.c:369:kms_rtp_synchronizer_process_rtp_buffer_mapped:<KmsRtpSynchronizer@0x7f9e38008270> Received an unsorted RTP buffer when expecting sorted (ssrc: 4266778376, seq: 13891, ts: 423381284, ext_ts: 423381284). Moving to unsorted mode
Nov 01 17:30:30 kurento kurento.sh[2577]: Segmentation fault (thread 140317160294144, pid 2579)
Nov 01 17:30:30 kurento kurento.sh[2577]: Stack trace:
Nov 01 17:30:30 kurento kurento.sh[2577]: [g_socket_send_message]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0:0x7B044
Nov 01 17:30:30 kurento kurento.sh[2577]: [nice_output_stream_new]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libnice.so.10:0x2ACBF
Nov 01 17:30:30 kurento kurento.sh[2577]: [nice_output_stream_new]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libnice.so.10:0x2AF3B
Nov 01 17:30:30 kurento kurento.sh[2577]: [nice_agent_recv_nonblocking]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libnice.so.10:0x12AE9
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_nice_src_get_type]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstnice15.so:0x36B2
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_nice_sink_get_type]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstnice15.so:0x3F3B
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_base_sink_do_preroll]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x2A151
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_base_sink_do_preroll]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x2B620
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_flow_get_name]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E832
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_pad_push_list]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x76793
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_proxy_pad_chain_list_default]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x5F6B3
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_flow_get_name]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E832
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_pad_push_list]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x76793
Nov 01 17:30:30 kurento kurento.sh[2577]: 0x1B412 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstcoreelements.so
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_flow_get_name]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E832
Nov 01 17:30:30 kurento kurento.sh[2577]: [gst_pad_push_list]
Nov 01 17:30:30 kurento kurento.sh[2577]: /usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x76793
Nov 01 17:30:30 kurento systemd[1]: kurento.service: Main process exited, code=exited, status=134/n/a
Nov 01 17:30:30 kurento systemd[1]: kurento.service: Unit entered failed state.
Nov 01 17:30:30 kurento systemd[1]: kurento.service: Failed with result 'exit-code'.
Nov 01 17:31:12 kurento systemd[1]: kurento.service: Service hold-off time over, scheduling restart.
Nov 01 17:31:12 kurento systemd[1]: Stopped Kurento Media Server.
Nov 01 17:31:12 kurento systemd[1]: Started Kurento Media Server.

**KMS Version**:

Version: 6.7.0~1.g6ebaa27
Found modules:
        Module: 'core' version '6.6.3'
        Module: 'elements' version '6.6.3'
        Module: 'filters' version '6.7.0~1.g0314843'

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

ii  gir1.2-gst-plugins-base-1.5            1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gir1.2-gstreamer-1.5                   1.8.1.1.xenial~20170725152356.170.0d6031b  amd64        Description: GObject introspection data for the GStreamer library
ii  gstreamer1.5-libav:amd64               1.8.2.1.xenial~20170725171352.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                0.1.15.xenial~20170824152246.83.28531a4    amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64         1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64        1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64        1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64        1.8.1.1.xenial~20170725170621.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64          1.8.1.1.xenial~20170725161537.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                   1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-cmake-utils                        1.5.0.xenial~20170811181647.1.68ec0fc      all          Kurento cmake utils
ii  kms-core-6.0                           6.6.3.xenial.20170811182512.2704d13        amd64        Kurento core module
ii  kms-core-6.0-dev                       6.6.3.xenial.20170811182512.2704d13        amd64        Kurento core module
ii  kms-elements-6.0                       6.6.3.xenial.20170812234356.9e3fff4        amd64        Kurento elements module
ii  kms-elements-6.0-dev                   6.6.3.xenial.20170812234356.9e3fff4        amd64        Kurento elements module
ii  kms-filters-6.0                        6.7.0.xenial~20170813001324.1.0314843      amd64        Kurento filters module
ii  kms-filters-6.0-dev                    6.7.0.xenial~20170813001324.1.0314843      amd64        Kurento filters module
ii  kms-jsonrpc-1.0                        1.2.0.xenial~20170811181902.1.8cee9d8      amd64        Kurento jsonrpc library
ii  kms-jsonrpc-1.0-dev                    1.2.0.xenial~20170811181902.1.8cee9d8      amd64        Kurento jsonrpc library
ii  kmsjsoncpp                             1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dev                         1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsonrpc library
ii  kurento-media-server-6.0               6.7.0.xenial~20170813003033.1.6ebaa27      amd64        Kurento Media Server
ii  kurento-module-creator-4.0             4.0.8.xenial~20170725174309.1.9662c2f      all          Kurento module creator
ii  libgstreamer-plugins-bad1.5-0:amd64    1.8.1.1.xenial~20170725164047.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64   1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.5-dev       1.8.1.1.xenial~20170725154709.55.7b19cfd   amd64        GStreamer development files for libraries from the "base" set
ii  libgstreamer1.5-0:amd64                1.8.1.1.xenial~20170725152356.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-dev                    1.8.1.1.xenial~20170725152356.170.0d6031b  amd64        GStreamer core development files
ii  libnice-dev                            0.1.15.xenial~20170824152246.83.28531a4    amd64        ICE library (development files)
ii  libnice10:amd64                        0.1.15.xenial~20170824152246.83.28531a4    amd64        ICE library (shared library)

**Client libraries**
- Language: Nodejs. 
- Version: v6.2.2

**Browsers tested**
 master
have tested this issue:
- Chrome:
- Firefox:
- Native:

**System description:**
	Please describe your setup (where is KMS located, where are the
	clients, STUN, TURN...)

**What steps will reproduce the problem?**
Tested with operating systems:  Windows, Ubunto 14.04, Android 
With 5 - 15 clients witch different machines from different location. 

Any help will be very much appreciated.

**Comment by j1elo** [comment] 2018-04-12 15:45
Duplicate of #247 
We'll be tracking progress affecting this crash on that other issue

**Closed** 2018-11-15 12:01 UTC
