### ISSUE TITLE
Will Kurento move to newer version of GStreamer?

### ISSUE THREAD

**Issue by lucifer1004** [Kurento/bugtracker#292] opened 2018-08-12 14:53 UTC
As GStreamer implements the webrtcbin in the newest 1.14 version, I wonder whether Kurento developers will consider moving to that version and simplifying the WebRtcEndpoint via webrtcbin?

**Comment by micaelgallego** [comment] 2018-08-13 09:56
It is planned to explore GStreamer update in the following months (around
Q4 2018 / Q1 2019). But we can not promise anything because it is a huge
task.

Regards

**Comment by lucifer1004** [comment] 2018-08-13 10:52
@micaelgallego Actually, I have successfully compiled the whole Kurento project based on GStreamer-1.14.2，and the Kurento-Hello-World Java tutorial can work fine. However, not all KMS elements work fine. e.g., the KMSAudiomixer fails to produce mixed audio. If possible, I can share some of my experience with you, and I hope that might be helpful to your further development.

**Comment by micaelgallego** [comment] 2018-08-13 13:25
This is the problem, that we need to carefully review and fix every feature provided by Kurento when we update.

Thank you for offering your help. When we start working on it, we will announce it and if we find problems we will ask community to help us. 

In the mean time, if you can share with us a document with the steps you have followed to update GStreamer in KMS and how have you solved the problems found, we will appreciate it.

**Comment by 823639792** [comment] 2019-04-28 09:07
Has the gstreamer update progressed?

**Comment by micaelgallego** [comment] 2019-04-28 09:54
We plan to dedicate time to this in the following weeks

**Comment by vanhungoz** [comment] 2020-06-19 02:24
@lucifer1004  could you share a document with the step by step you have used to update GStreamer in KMS?
Thank you so much!

**Comment by j1elo** [comment] 2023-01-18 14:38
Closing because not a bug.

**Closed by j1elo** 2023-01-18 14:38 UTC
