### ISSUE TITLE
when run project on ip show reconnect to server 1 100 undefined

### ISSUE THREAD

**Issue by miaaad** [Kurento/bugtracker#250] opened 2018-05-05 12:57 UTC
this is all the log in terminal show me  . thanks 

i think signaling is ok when show in locale server i want run show this  .

just dont show any thing or voice to other user 

Kurento Tutorial started
Open https://192.168.1.109:8443/ with a WebRTC capable browser
Connection received with sessionId 1
Connection received with sessionId 2
Connection 2 received message  { id: 'register', name: 'aa' }
Connection 1 received message  { id: 'register', name: 'bb' }
Connection 2 received message  { id: 'call',
  from: 'aa',
  to: 'bb',
  sdpOffer: 'v=0\r\no=mozilla...THIS_IS_SDPARTA-59.0.2 2429050803097837916 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 64:E6:6A:90:4F:D3:F5:79:66:E2:1C:24:42:88:65:15:82:B4:30:DD:40:A0:02:51:D8:05:65:CD:15:88:35:FC\r\na=group:BUNDLE sdparta_0 sdparta_1\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:101 0-15\r\na=ice-pwd:1daee3085fd3d7a3347e11060c5455eb\r\na=ice-ufrag:4e663700\r\na=mid:sdparta_0\r\na=msid:{f9fd939d-82ae-4140-aebe-7056eac2b9c8} {3c002f7a-c18d-45d6-b3f4-b108e625f91e}\r\na=rtcp-mux\r\na=rtpmap:109 opus/48000/2\r\na=rtpmap:9 G722/8000/1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:101 telephone-event/8000\r\na=setup:actpass\r\na=ssrc:403841869 cname:{15b18a5f-36eb-4886-b4a1-e16e854b565e}\r\nm=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1\r\na=fmtp:120 max-fs=12288;max-fr=60\r\na=fmtp:121 max-fs=12288;max-fr=60\r\na=ice-pwd:1daee3085fd3d7a3347e11060c5455eb\r\na=ice-ufrag:4e663700\r\na=mid:sdparta_1\r\na=msid:{f9fd939d-82ae-4140-aebe-7056eac2b9c8} {6bf105a2-c314-4c30-a608-f79451e9bdc7}\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:120ccm fir\r\na=rtcp-fb:120 goog-remb\r\na=rtcp-fb:121 nack\r\na=rtcp-fb:121 nack pli\r\na=rtcp-fb:121 ccm fir\r\na=rtcp-fb:121 goog-remb\r\na=rtcp-fb:126 nack\r\na=rtcp-fb:126 nack pli\r\na=rtcp-fb:126 ccm fir\r\na=rtcp-fb:126 goog-remb\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 goog-remb\r\na=rtcp-mux\r\na=rtpmap:120 VP8/90000\r\na=rtpmap:121 VP9/90000\r\na=rtpmap:126 H264/90000\r\na=rtpmap:97 H264/90000\r\na=setup:actpass\r\na=ssrc:3417885046 cname:{15b18a5f-36eb-4886-b4a1-e16e854b565e}\r\n' }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:0 1 UDP 2122187007 192.168.1.113 46599 typ host',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3 1 UDP 2122252543 192.168.1.102 39543 typ host',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:6 1 TCP 2105458943 192.168.1.113 9 typ host tcptype active',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:7 1 TCP 2105524479 192.168.1.102 9 typ host tcptype active',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:0 2 UDP 2122187006 192.168.1.113 48710 typ host',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3 2 UDP 2122252542 192.168.1.102 35696 typ host',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:6 2 TCP 2105458942 192.168.1.113 9 typ host tcptype active',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:7 2 TCP 2105524478 192.168.1.102 9 typ host tcptype active',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:0 1 UDP 2122187007 192.168.1.113 37493 typ host',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3 1 UDP 2122252543 192.168.1.102 35028 typ host',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:6 1 TCP 2105458943 192.168.1.113 9 typ host tcptype active',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:7 1 TCP 2105524479 192.168.1.102 9 typ host tcptype active',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:0 2 UDP 2122187006 192.168.1.113 54332 typ host',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3 2 UDP 2122252542 192.168.1.102 53276 typ host',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:6 2 TCP 2105458942 192.168.1.113 9 typ host tcptype active',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:7 2 TCP 2105524478 192.168.1.102 9 typ host tcptype active',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:1 1 UDP 1685987327 176.65.204.56 15161 typ srflx raddr 192.168.1.113 rport 46599',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:4 2 UDP 1686052862 176.65.204.56 15164 typ srflx raddr 192.168.1.102 rport 35696',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:1 2 UDP 1685987326 176.65.204.56 15163 typ srflx raddr 192.168.1.113 rport 48710',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:1 1 UDP 1685987327 176.65.204.56 15165 typ srflx raddr 192.168.1.113 rport 37493',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:4 1 UDP 1686052863 176.65.204.56 15166 typ srflx raddr 192.168.1.102 rport 35028',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:1 2 UDP 1685987326 176.65.204.56 15167 typ srflx raddr 192.168.1.113 rport 54332',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:4 1 UDP 1686052863 176.65.204.56 15162 typ srflx raddr 192.168.1.102 rport 39543',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:4 2 UDP 1686052862 176.65.204.56 15168 typ srflx raddr 192.168.1.102 rport 53276',
     sdpMid: 'sdparta_1',
     sdpMLineIndex: 1 } }
Connection 2 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:2 2 UDP 1685987070 176.65.204.56 20793 typ srflx raddr 192.168.1.113 rport 48710',
     sdpMid: 'sdparta_0',
     sdpMLineIndex: 0 } }
Connection 1 received message  { id: 'incomingCallResponse',
  from: 'aa',
  callResponse: 'accept',
  sdpOffer: 'v=0\r\no=- 3932709037424468112 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:iEGz\r\na=ice-pwd:eZB94oxdKEPCF0xSjAYzUvAY\r\na=ice-options:trickle\r\na=fingerprint:sha-256 8B:4D:DC:18:BE:46:73:F2:40:BE:AB:6D:78:4D:A2:87:EB:BE:8D:9D:B2:41:58:A2:DA:02:F1:6E:8B:8C:D0:A5\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:334801156 cname:BSwZZohSknHmo5x8\r\na=ssrc:334801156 msid:Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx caa3be75-d1ab-462d-8ff6-cdeecc91cebe\r\na=ssrc:334801156 mslabel:Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx\r\na=ssrc:334801156 label:caa3be75-d1ab-462d-8ff6-cdeecc91cebe\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 123 127 122 125 107 108 109 124\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:iEGz\r\na=ice-pwd:eZB94oxdKEPCF0xSjAYzUvAY\r\na=ice-options:trickle\r\na=fingerprint:sha-256 8B:4D:DC:18:BE:46:73:F2:40:BE:AB:6D:78:4D:A2:87:EB:BE:8D:9D:B2:41:58:A2:DA:02:F1:6E:8B:8C:D0:A5\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:123 rtx/90000\r\na=fmtp:123 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 red/90000\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 ulpfec/90000\r\na=ssrc-group:FID 1686229641 1423886050\r\na=ssrc:1686229641 cname:BSwZZohSknHmo5x8\r\na=ssrc:1686229641 msid:Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx d20a8468-4c80-4ebb-89cb-ba2d8361b2a9\r\na=ssrc:1686229641 mslabel:Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx\r\na=ssrc:1686229641 label:d20a8468-4c80-4ebb-89cb-ba2d8361b2a9\r\na=ssrc:1423886050 cname:BSwZZohSknHmo5x8\r\na=ssrc:1423886050 msid:Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx d20a8468-4c80-4ebb-89cb-ba2d8361b2a9\r\na=ssrc:1423886050 mslabel:Jdli59Wr3lPB6lK51w2noGK3VM66aUlF6Ppx\r\na=ssrc:1423886050 label:d20a8468-4c80-4ebb-89cb-ba2d8361b2a9\r\n' }
Connection 1 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3467446226 1 udp 2122260223 192.168.1.109 63265 typ host generation 0 ufrag iEGz network-id 1 network-cost 10',
     sdpMid: 'audio',
     sdpMLineIndex: 0 } }
Connection 1 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3467446226 1 udp 2122260223 192.168.1.109 55649 typ host generation 0 ufrag iEGz network-id 1 network-cost 10',
     sdpMid: 'video',
     sdpMLineIndex: 1 } }
Connection 1 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:2150562594 1 tcp 1518280447 192.168.1.109 9 typ host tcptype active generation 0 ufrag iEGz network-id 1 network-cost 10',
     sdpMid: 'audio',
     sdpMLineIndex: 0 } }
Connection 1 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:2150562594 1 tcp 1518280447 192.168.1.109 9 typ host tcptype active generation 0 ufrag iEGz network-id 1 network-cost 10',
     sdpMid: 'video',
     sdpMLineIndex: 1 } }
reconnect to server 0 100 undefined
Connection 1 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:1340408166 1 udp 1686052607 176.65.204.56 15171 typ srflx raddr 192.168.1.109 rport 63265 generation 0 ufrag iEGz network-id 1 network-cost 10',
     sdpMid: 'audio',
     sdpMLineIndex: 0 } }
Connection 1 received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:1340408166 1 udp 1686052607 176.65.204.56 15172 typ srflx raddr 192.168.1.109 rport 55649 generation 0 ufrag iEGz network-id 1 network-cost 10',
     sdpMid: 'video',
     sdpMLineIndex: 1 } }
reconnect to server 1 100 undefined
reconnect to server 2 200 undefined
reconnect to server 3 300 undefined
reconnect to server 4 500 undefined
reconnect to server 5 800 undefined
reconnect to server 6 1300 undefined
reconnect to server 7 2100 undefined
reconnect to server 8 3400 undefined
reconnect to server 9 5500 undefined
Connection 2 closed
reconnect to server 10 8900 undefined
reconnect to server 11 10000 undefined
reconnect to server 12 10000 undefined
reconnect to server 13 10000 undefined
reconnect to server 14 10000 undefined
reconnect to server 15 10000 undefined
reconnect to server 16 10000 undefined
reconnect to server 17 10000 undefined
reconnect to server 18 10000 undefined
reconnect to server 19 10000 undefined
reconnect to server 20 10000 undefined
reconnect to server 21 10000 undefined
reconnect to server 22 10000 undefined
reconnect to server 23 10000 undefined
reconnect to server 24 10000 undefined
reconnect to server 25 10000 undefined
reconnect to server 26 10000 undefined
reconnect to server 27 10000 undefined
reconnect to server 28 10000 undefined
reconnect to server 29 10000 undefined
reconnect to server 30 10000 undefined
reconnect to server 31 10000 undefined
reconnect to server 32 10000 undefined
reconnect to server 33 10000 undefined
reconnect to server 34 10000 undefined
Connection 1 closed
reconnect to server 35 10000 undefined
reconnect to server 36 10000 undefined

**Comment by sraza295** [comment] 2020-07-08 20:08
@miaaad @abhilashfancy @johnnyharpertesting8 
This problem occurs when KMS is stopped.
So check it.

**Comment by j1elo** [comment] 2020-07-09 10:52
@sraza295 thanks for helping suggest possible cause.
I'm closing as not a bug because the issue is old and probably was that KMS process stopped anyway.

**Closed by j1elo** 2020-07-09 10:52 UTC
Labels: not-a-bug
