### ISSUE TITLE
kurento-media-server Segmentation fault

### ISSUE THREAD

**Issue by isuker** [Kurento/bugtracker#53] opened 2016-03-23 07:33 UTC
I am using Kurento Media Server (6.4.0) and kurento-room.  

env:
---------------------------------------------------
server:
os............: ubuntu14.04
cpu..........: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, 4core
memory....: 8G
------------------
clients:
several macbook chrome browser.
---------------------------------------------------

when we run with several rooms, Kurento media server crashes 

logs:
-----------------------------------------------------------------------------------------------------------------------
```
Warning: Still 1 object/s alive

(kurento-media-server:1333): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(kurento-media-server:1333): GLib-GObject-CRITICAL **: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (kurento-media-server:1333): CRITICAL **: gst_video_frame_map_id: assertion 'info->width <= meta->width' failed
......................
** (kurento-media-server:1701): CRITICAL **: gst_video_frame_map_id: assertion 'info->width <= meta->width' failed
[31;1mSegmentation fault[0m (thread [33;1m140007894537984[0m, pid [33;1m1701[0m)
Stack trace:
[34;1m[g_type_check_instance_cast][0m
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0[32;1m:0x34984[0m
[34;1m[check_if_flow_media][0m
/usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.6[32;1m:0x1A9A0[0m
[34;1m[gst_structure_fixate][0m
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0[32;1m:0x99E44[0m
[34;1m[g_test_get_filename][0m
/lib/x86_64-linux-gnu/libglib-2.0.so.0[32;1m:0x70965[0m
[34;1m[start_thread][0m
/lib/x86_64-linux-gnu/libpthread.so.0[32;1m:0x8182[0m
[34;1m[clone][0m
/lib/x86_64-linux-gnu/libc.so.6[32;1m:0xFA47D[0m
\00
```

-----------------------------------------------------------------------------------------------------------------------
Thanks! And sorry for the long description :)

**Comment by dfernandezlop** [comment] 2016-03-23 12:32
Hi,

Could you check with the development version of KMS [1]? We had an issue in the function `check_if_flow_media` but it is resolved in the master branch.

Thanks.
[1] http://doc-kurento.readthedocs.org/en/stable/mastering/kurento_development.html

**Comment by isuker** [comment] 2016-03-23 13:24
thanks for your reply, and i had check the kms version

webrtc@xxx:~$ kurento-media-server -v
Version: 6.4.0
Found modules:
	Module: 'core' version '6.4.0'
	Module: 'elements' version '6.4.0'
	Module: 'filters' version '6.4.0'
	Module: 'pointerdetector' version '6.4.0'
webrtc@xxx:~$

and I found the new version at
http://ubuntu.kurento.org/pool/kms6/k/kurento-media-server-6.0/
......
kurento-server_6.4.1~20160323111652.5.g15f6a5f.trusty_amd64.deb	2016-03-23 11:24	31K	 

is this work ok?
-------------------
Thanks!

**Comment by dfernandezlop** [comment] 2016-03-23 14:39
Yes, it is the newest package. If you configure the dev repository, you can install this package via apt-get.

**Comment by dfernandezlop** [comment] 2016-03-28 11:04
Any update?

**Comment by igracia** [comment] 2016-04-08 12:17
@isuker Did you check with the latest version? Any info you can provide? Please come back to this issue. Otherwise we will close it.

**Comment by mcuervoe** [comment] 2016-04-12 14:36
I had the issue with the check_if_flow_media and I moved to the kurento version 6.4.1~20160323111652 as suggested

The media server starts but now kurento is not able to load the modules that I have developed (and they were working with version 6.4.0). The message that I get is:

0:00:00.618559622     1      0x1f27560 WARN    KurentoModuleManager ModuleManager.cpp:61:loadModule: Module /usr/lib/x86_64-linux-gnu/kurento/modules/libkmseidfiltersmodule.so cannot be loaded: /usr/lib/x86_64-linux-gnu/libkmseidfiltersimpl.so.0: undefined symbol: _ZTv0_n88_N7kurento15MediaObjectImpl16getMediaPipelineEv

BTW, the modules have been recompiled with the new version 6.4.1 of kurento. 

I also try with the latest night build of 6.4.1~20160412102839 without success. Any help?

**Comment by jcaden** [comment] 2016-04-12 14:44
Try updating `kms-core` and `kms-elements` and recompile them again, cleaning first.

**Comment by mcuervoe** [comment] 2016-04-12 15:33
I didn't get `kms-core` nor `kms-elements` from the sources but from the apt package. Do I need to compile them manually?

**Comment by jcaden** [comment] 2016-04-13 05:00
No, but you have to be sure that you have the last version

**Comment by mcuervoe** [comment] 2016-04-13 12:04
Jose Antonio, you were right. I need to get sure that I was using the last version. With the lastest package installed I have not problems loading my filters. However, I keep having the error

```
** (kurento-media-server:1): CRITICAL **: gst_video_frame_map_id: assertion 'info->width <= meta->width' failed
```

For your information:

 `kurento-media-server -v` produces
```
Version: 6.4.1~10.gdb95fa3
Found modules:
        Module: 'core' version '6.4.1~53.gccaed1f'
        Module: 'eidfilters' version '0.0.1-dev'
        Module: 'elements' version '6.4.1~34.gdbffe9a'
        Module: 'filters' version '6.4.1~4.g33b7020'
```

The packages I have installed are:

```
 dpkg -l | grep kurento
ii  kurento-media-server-6.0             6.4.1~20160412102839.10.gdb95fa3.trusty    amd64        Kurento Media Server
ii  kurento-media-server-6.0-dev         6.4.1~20160412102839.10.gdb95fa3.trusty    amd64        Kurento media server, development files and tools
ii  kurento-module-creator-4.0           4.0.5~20160407093752.7.g3115217.trusty     all          Kurento module creator
```

**Comment by jcaden** [comment] 2016-04-13 12:11
Not sure, but this could be related to your video filter. In order to make server fail when this warning is reached, define `G_DEBUG=fatal_warnings` on your `/etc/default/kurento-media-server-6.0`this way you will get a trace of the point where this warning is reached.

**Comment by mcuervoe** [comment] 2016-04-13 13:03
I have defined `G_DEBUG=fatal_warnings` on my `/etc/default/kurento-media-server-6.0` and rerun the test. I get again the assertion CRITICAL message, but `find / -type f -name core` do not find any core dump in my system.

**Comment by jcaden** [comment] 2016-04-13 15:18
Could it be handled by apport?

**Comment by mcuervoe** [comment] 2016-04-14 11:01
Sorry, don't know what apport is. Let me investigate it and I will get back to you.

In the meantime, I did another test with a bare kurento media server 6.4.1 without the filters I have developed, and the CRITICAL message is still reproduced.

Now `kurento-media-server -v` produces

```
Found modules:
        Module: 'core' version '6.4.1~53.gccaed1f'
        Module: 'elements' version '6.4.1~34.gdbffe9a'
        Module: 'filters' version '6.4.1~4.g33b7020'
```

Just for your information, I am testing the kurento-one2one-call-recording app from the java tutorials. To automate the testing I use two chromes with these paramters: 

```
/usr/bin/google-chrome  --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --use-file-for-fake-video-capture=/home/vagrant/Downloads/example.y4m --user-data-dir=/tmp/user1

/usr/bin/google-chrome  --use-fake-ui-for-media-stream --use-fake-device-for-media-stream --use-file-for-fake-video-capture=/home/vagrant/Downloads/akiyo_qcif.y4m --user-data-dir=/tmp/user2
```
First video can be found [here](http://samples.mplayerhq.hu/yuv4mpeg2/example.y4m.bz2)
Second video can be found [here](https://media.xiph.org/video/derf/y4m/akiyo_qcif.y4m)

**Comment by mcuervoe** [comment] 2016-04-15 08:18
No luck with apport either:

1. I set the `/etc/apport/crashdb.conf`as explained [here](https://wiki.ubuntu.com/Apport) with a # in front of the line `'problem_types': ['Bug', 'Package'],`
2. I executed the test with `G_DEBUG=fatal_warnings` at the end of `/etc/default/kurento-media-server-6.0`
3. the critical message is reproduced
4. No file is produced in `/var/crash`, which I think it is what you expected to happen

However I have localize the component that is producing the message: if I disconnect the FaceOverlayFilter from the pipleline, the critical message is not produced. I hope this can help you to narrow your search. 

Let me know what can I do to help you with this.

**Comment by kirushyk** [comment] 2016-04-23 12:56
I had very strange FaceOverlayFilter-related crash caused by `g_object_set (queue, "max-size-time", LEAKY_TIME, "leaky", 2 /*downstream */ , NULL);`
But now it's solved by https://github.com/Kurento/kms-core/commit/8f0a42bf49f82bfae41ae255d792e660791ba89d

**Comment by dfernandezlop** [comment] 2016-05-11 07:59
Any update on this?

**Comment by kirushyk** [comment] 2016-05-11 09:44
Some weeks ago there was code with incorrect type of argument in variable argument list of g_object_set, and that code caused strange crashes. Code appeared in master branch and has been removed soon after.

**Comment by dfernandezlop** [comment] 2016-05-11 09:55
Ok, then I'm going to close the bug. If you have the same problem again, please feel free to come back.

Thanks for report.

**Closed by dfernandezlop** 2016-05-11 09:55 UTC

**Comment by kirushyk** [comment] 2016-05-11 11:36
Sorry, in link I sent few message ago bug was introduced, not fixed. In next revision of that file changes seems to be reverted.
