### ISSUE TITLE
KMS-CORE: SPS/PPS information not provided to clients during H264 video call

### ISSUE THREAD

**Issue by leetal** [Kurento/bugtracker#321] opened 2018-12-17 12:12 UTC
SPS/PPS information is not sent to clients when H264 has been negotiated and video is flowing. This will cause iOS (and perhaps other clients as well) to not regain decoding video if the application is for example backgrounded and then again maximized. This is due to the fact that the IDR frames does not embed PPS/SPS information if that parameter is not set.

**KMS Version**:

6.9.0

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.8.2.1.xenial\~20181023163456.96.493eee4   amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.15-1kurento2                           amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1.xenial\~20181023161445.100.3db37b1  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1.xenial\~20181023154838.55.7b19cfd   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1.xenial\~20181023160032.112.9ee4248  amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1.xenial\~20181023162927.89.2685b0f   amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1.xenial\~20181023160032.112.9ee4248  amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1.xenial\~20181023154838.55.7b19cfd   amd64        GStreamer plugins for X11 and Pango
ii  kms-core                             6.9.0.xenial.20181210200440.bee54d3        amd64        Kurento Core module
ii  kms-elements                         6.9.0.xenial.20181210201219.6d6f745        amd64        Kurento Elements module
ii  kms-filters                          6.9.0.xenial.20181210201843.08e687c        amd64        Kurento Filters module
ii  kms-jsonrpc                          6.9.0.xenial.20181210195903.71b45ec        amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3.xenial.20181023152331.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.9.0.xenial.20181210202449.f940867        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1.xenial\~20181023161445.100.3db37b1  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1.xenial\~20181023154838.55.7b19cfd   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1.xenial\~20181023153550.170.0d6031b  amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.15-1kurento2                           amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1.xenial\~20181023161445.100.3db37b1  amd64        GStreamer plugins from openh264

**Client libraries**
- Language: Java
- Version: 6.8.0(?)

**Browsers tested**
- Chrome: NO_TEST
- Firefox: NO_TEST
- Native: iOS, Android, Windows

**System description:**
Standard setup.  Kurento-client on same machine as kurento-media-server. 

**What steps will reproduce the problem?**
1. On iOS, receive arbitrary H264 video.
2. Minimize application so that decoder cannot run (not allowed in background).
3. Maximize application again, video will be black.

**What is the expected result?**
Continue decode frames as nothing had happened.

**What happens instead?**
Video is black and decoding fails since the IDR NAL units does not contain format information.

**Please provide any additional information below.**
I have done some digging and found out that the "config-interval" gstreamer parameter is not set due to wrong type-checks. Newer versions of gstreamer have updated this parameter to support `gint` instead of the former `guint`. Thus this parmeter is not set since you have a check that verifies its type as G_TYPE_UINT (guint). My patch also modifies the configuration interval to "-1" instead of "1" which essentially means that whenever the clients ask for a H264 keyframe, also embed SPS/PPS information in the NAL unit IDR frames.
(gstreamer docs: [HEAD ref: config-interval](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-rtph264pay.html#GstRtpH264Pay--config-interval)) 

I have patched (and tested) a 6.9.0 build of KMS and can verify this indeed fixes the issue!
[See attached patch file.](https://github.com/Kurento/bugtracker/files/2685919/6.9.0_kms-core_config-interval.txt) I can provide a PR to kms-core if that is applicable as well.

**Comment by prlanzarin** [comment] 2019-01-30 03:07
@leetal @j1elo Seems like I was chasing this issue too, but didn't see this in the bugtracker.
I had opened a pull request (https://github.com/Kurento/kms-core/pull/15) with a patch very much like the one @leetal described before I've seen that. Nonetheless, I've confirmed that the forked version of gstreamer does depend on the G_INT type, so the patch is sounding.

**Comment by j1elo** [comment] 2019-01-30 10:40
Good, sorry for the delay, we're pretty busy porting everything to Ubuntu 18.04.
@leetal your patch seems more complete than Kurento/kms-core#15 especially by taking care of the actual values set to "config-interval" (-1 instead of 1), so please could you open a PR? I'll review and merge.

**Comment by prlanzarin** [comment] 2019-01-30 14:14
My only issue with setting -1 instead of 1 is that gstreamer tends to insert buffered SPS/PPS for every IDR-slice when H.264 is in that format. That doesn't seem to happen with fragmentation unit based streams, but since legscy, pure RTP endpoints tend to rely on IDR slices, I'd be careful setting that value.

Inserting SPS/PPS makes some decoders stutter and increases the stream size considerably. It's more of a gstreamer issue than Kurento.

**Comment by prlanzarin** [comment] 2019-01-30 14:18
I'll provide a pcap asap with the aforementioned behaviour with -1 just so you guys can see what I'm trying to say.

**Comment by prlanzarin** [comment] 2019-01-30 15:01
![sps-pps-minus1](https://user-images.githubusercontent.com/4529051/51989489-53b77a00-248e-11e9-9c9b-5079e18aba92.png)
![sps-pps-1](https://user-images.githubusercontent.com/4529051/51989490-53b77a00-248e-11e9-855a-bdeefc1a068a.png)

Two images in annex. It's a pure RTP endpoint receiving two streams from Kurento. The garbled one has  config-interval set to -1, while the ok one has config-interval set to 1.

Here are the pcaps of the tests depicted in the images (cf-1: config-interval = 1; cf-minus-1: config-interval = -1). They've been filtered to show only the incoming streams **from** Kurento.
https://drive.google.com/drive/folders/1YbNP73lEShTfRLPfvM473bI5FNH0p8cQ?usp=sharing

@leetal Have you tested setting `1` on your setup? FIY, we've also been using 1 for our webrtc endpoints.

**Comment by leetal** [comment] 2019-01-30 15:09
@prlanzarin Yes we have tested both and the only difference we can see locally is the fact that it takes 1 sec for the stream to regain control (since setting 1 will cause SPS/PPS information to be sent once every second, whilst -1 sends SPS/PPS with every IDR-slice). I'll agree that -1 is probably too aggressive and can cause pure RTP to never fully regain decoding capabilities since it will constantly have to adapt to the SPS/PPS NALs. I'd agree that setting 1 instead of -1 will significantly reduce the total transfer sizes and is also probably better for everyone (legacy RTP as well as WebRTC-black-magic guys). Setting 1 is still far better than the functionality right now (totally broken).

I'll open a PR with the config-interval set to 1 since that was the old behaviour as well.

**Comment by prlanzarin** [comment] 2019-01-30 15:14
I've also updated my PR with the paytreebin modification of your patch, but feel free to close that one and open a new one with your patch.

**Comment by leetal** [comment] 2019-01-30 15:14
Nah, let's use your then :)

**Comment by j1elo** [comment] 2019-03-11 10:35
Merged https://github.com/Kurento/kms-core/pull/15, hopefully this solves the issue with H.264 SPS and PPS nal units

**Closed by j1elo** 2019-03-11 10:35 UTC
