### ISSUE TITLE
Kurento crash on releasing pipeline

### ISSUE THREAD

**Issue by Lisitskiy** [Kurento/bugtracker#88] opened 2016-06-27 13:47 UTC
**KMS Version**:  6.5.0

`0:00:00.032077048    69       0xa3f210 INFO    KurentoModuleManager ModuleManager.cpp:156:loadModules: Looking for modules in /usr/lib/x86_64-linux-gnu/kurento/modules

0:00:00.033347252    69       0xa3f210 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so

0:00:00.033494432    69       0xa3f210 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded filters version 6.5.0 generated at May 30 2016 15:55:46

0:00:00.034132370    69       0xa3f210 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so

0:00:00.034258820    69       0xa3f210 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded core version 6.5.0 generated at May 30 2016 14:20:56

0:00:00.050304328    69       0xa3f210 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so

0:00:00.050442967    69       0xa3f210 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded elements version 6.5.0 generated at May 30 2016 15:46:36

Version: 6.5.0
Found modules:
        Module: 'core' version '6.5.0'
        Module: 'elements' version '6.5.0'
        Module: 'filters' version '6.5.0'
`

**Other libraries versions**:

`ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer

ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)

ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set

ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set

ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set

ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set

ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio

ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango

ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module

ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module

ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module

ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library

ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library

ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server

ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set

ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set

ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements

ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)
`

**Client libraries**
- Language: Node.js
- Version:

**System description:**
	TURN SERVER

**What steps will reproduce the problem?**
1. Create "MediaPipeline"
2. Pipe "PlayerEndpoint" (with uri rtmp://<path to stream> in param)
3. Release  created MediaPipeline or PlayerEndpoint 

**What is the expected result?**
Expecting resul - pipeline is released correctly

**What happens instead?**
Kms is crash with error

```
0:02:43.372225322     1 0x7f9180002330 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:423:processMessage: Response: >{"id":295,"jsonrpc":"2.0","result":{"sessionId":"3eb467e5-7053-4cd2-b926-2badb2191c16"}}<
0:02:43.382635504     1      0x13ce4f0 DEBUG        KurentoMediaSet MediaSet.cpp:461:async_delete: Destroying PlayerEndpoint -> 2cafd34a-f211-450b-badf-0f1bdc85a559_kurento.MediaPipeline/94fd2a23-a22a-47c8-b8e3-9713299dedc5_kurento.PlayerEndpoint
0:02:43.386298437     1 0x7f9178002670 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:421:processMessage: Message: >{"jsonrpc":"2.0","method":"unsubscribe","params":{"object":"2cafd34a-f211-450b-badf-0f1bdc85a559_kurento.MediaPipeline/d88dee4d-9123-4433-a129-18d5046ce271_kurento.WebRtcEndpoint","subscription":"45b0de2c-9a7c-4472-8596-c4f4cc63a933","sessionId":"3eb467e5-7053-4cd2-b926-2badb2191c16"},"id":296}<
0:02:43.386424729     1 0x7f9178002670 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:423:processMessage: Response: >{"id":296,"jsonrpc":"2.0","result":{"sessionId":"3eb467e5-7053-4cd2-b926-2badb2191c16"}}<
0:02:43.386477242     1 0x7f9178002670 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:421:processMessage: Message: >{"jsonrpc":"2.0","method":"unsubscribe","params":{"object":"2cafd34a-f211-450b-badf-0f1bdc85a559_kurento.MediaPipeline/94fd2a23-a22a-47c8-b8e3-9713299dedc5_kurento.PlayerEndpoint","subscription":"fa3230d2-31f3-4648-ab9c-5aacd1610682","sessionId":"3eb467e5-7053-4cd2-b926-2badb2191c16"},"id":297}<
0:02:43.386597929     1 0x7f9178002670 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:423:processMessage: Response: >{"id":297,"jsonrpc":"2.0","result":{"sessionId":"3eb467e5-7053-4cd2-b926-2badb2191c16"}}<

Segmentation fault (thread 140262726678272, pid 1)
Stack trace:
[RTMP_ReadPacket]
/usr/lib/x86_64-linux-gnu/librtmp.so.1:0xA824
[RTMP_GetNextMediaPacket]
/usr/lib/x86_64-linux-gnu/librtmp.so.1:0xE927
[RTMP_GetNextMediaPacket]
/usr/lib/x86_64-linux-gnu/librtmp.so.1:0xEA25
[RTMP_Read]
/usr/lib/x86_64-linux-gnu/librtmp.so.1:0xF46C
0x2613 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstrtmp.so
[gst_base_src_wait_playing]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x2DDA9
[gst_base_src_wait_playing]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x2F8F3
[gst_tag_setter_get_tag_merge_mode]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x9FD7E
[g_thread_pool_new]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x712FE
[g_test_get_filename]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x70965
[start_thread]
/lib/x86_64-linux-gnu/libpthread.so.0:0x8184
[clone]
```

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**
In viewer mode - I can see transcoded stream from rtmp correctly.
But when I try to release pipeline which contains a player - kms crashes.
If I do not use release of pipeline  - kms works normally...
All this can be reproduced on docker image of kurento

**Comment by jcaden** [comment] 2016-06-27 14:33
@Lisitskiy Where did you get kurento docker image? Did you built it yourself?

Are all this libraries version for the ones installed in the docker container or are they get from the host?

**Comment by Lisitskiy** [comment] 2016-06-27 14:38
Hi.
I get it from https://hub.docker.com/r/kurento/kurento-media-server/
All from docker

Before testing this on docker image - i have received same crash on kms installed from doc manual.

**Comment by jcaden** [comment] 2016-06-27 14:44
@rbenitez Can you try to reproduce the bug in a test? Thanks.

**Comment by rbenitez** [comment] 2016-06-27 14:47
@jcaden yes, we will add this into ours planification

**Comment by rbenitez** [comment] 2016-09-02 09:59
Hi @Lisitskiy, 

I'm working in this test, but I have seen that you used a "PlayerEndpoint" (with uri **rtmp**:// in param), but rtmp uri is not supported. Maybe, your uri was "rtsp://"? If your uri was "rtsp://", please type here.

Please, check the documentation about the [PlayerEndPoint](https://doc-kurento.readthedocs.io/en/latest/_static/langdoc/javadoc/org/kurento/client/PlayerEndpoint.html).

Best

**Comment by Lisitskiy** [comment] 2016-09-02 10:24
Hello @rbenitez 
I am using **rtmp//**
And all works, exept a destroing of pipeline

**Comment by rbenitez** [comment] 2016-09-02 10:27
Please, could you tell us the URI you are using?

**Comment by jcaden** [comment] 2016-09-02 10:30
That is why rtmp is not officially supported (see that in the documentation that @rbenitez linked there is not rtmp urls), because the gstreamer elements that manage rtmp are not stable enough to use them in production. First step will be to fix them and then we can include this functionality to kms.

As the bug is related to a unsupported functionality I'm closing the bug.

**Closed by jcaden** 2016-09-02 10:30 UTC
Labels: bug, kms
