### ISSUE TITLE
Very large latency when webrtc client & KMS in different network

### ISSUE THREAD

**Issue by leecris** [Kurento/bugtracker#44] opened 2016-03-11 02:00 UTC
Hi, 

I posted question in https://groups.google.com/forum/#!topic/kurento/7S2ESeYRYJ4 but Jose said I should post here.

Enviroment setup:
KMS - 6.4.0 deployed in Ubuntu 14.04
Nodejs - deployed in Ubuntu 14.04
Camera: Logitech C920 HD
VLC: v2.2.x
Client: Chrome v48.0.2564.116 m

Running:

- Streaming RTSP with VLC by command:
cvlc -vvv v4l2:///dev/video1 --sout '#transcode{vcodec=h264,fps=25,width=1280,height=720,vb=800,acodec=none}:rtp{sdp=rtsp://:8554/}'

- Nodejs:
Development from one2many example: 
Server: create PlayerEndpoint {useEncodedMedia:false} -> create WebRTCEndpoint. Setup outputBitrate in MediaElement.conf.ini = 1500000
Client: using lastest adapter.js, kurento-utils, setup 
`mediaConstraints: {
	audio: false,
	 frameRate: {min: 20},
	 width: {min: 640, ideal: 1280},
	height: {min: 480, ideal: 720},
	aspectRatio: 1.5
}`

`configuration: {
       iceServers: [{"urls": "stun:xx.xx.xx.xx:80"},{"urls": "turn:xx.xx.xx.xx:80?transport=udp","credential":"xxxxxxx","username":"xxx"},{"urls": "turn:xx.xx.xx.xx:80?transport=tcp","credential":"xxxxxxx","username":"xxx"}]
}`

Result:

- Local network: both presenter & viewer can see very well high quality video with same outputBitrate setup before.

- Outsite local: Almost cannot see video, sometime when camera moving, framerate received jump to 25 and back to 3-4, audio still have delay but not very long like video.

Please help me check this issue

**Comment by igracia** [comment] 2016-03-11 10:50
Can you provide some info about the network conditions of WebRTC clients? Please post screenshots of webrtc-internals after some minutes, so we can see what's going on in there.

Have you checked with different clients and from different locations/networks?

**Comment by igracia** [comment] 2016-03-23 12:47
@leecris could you check in different networks? I'll be closing the issue if we don't get any feedback in some time.

**Comment by leecris** [comment] 2016-03-29 09:28
Hi igracia!

I'm sorry for late reply. I posted a screenshot of webrtc-internals when I view in different network.

![sc1](https://cloud.githubusercontent.com/assets/10285820/14103613/3009e416-f5cb-11e5-9803-02af95da3895.jpg)

**Comment by igracia** [comment] 2016-03-29 16:44
Have you tried from even a different location? You have soooo many losses that it's no surprise you are lagging.

**Comment by leecris** [comment] 2016-03-30 01:36
Different network, different location. I tried both but result is the same. That issue cause network speed or another things? Can you give me some reason of that?

**Comment by igracia** [comment] 2016-03-30 07:41
Well, packetsLost graph is terrible. You must have some connection issue.

**Comment by leecris** [comment] 2016-03-30 08:23
I tried another webrtc app and it work fine within current 2 network. Kurento demo have packet lost and Framerate too low.
Can you suggest some reason so I can check? Firewall, bandwidth...?
Thanks!

**Comment by leecris** [comment] 2016-03-30 08:26
Another question, how can I change output of Kurento is H264?

**Comment by igracia** [comment] 2016-03-30 08:35
I'd say both firewall and bandwidth. Can you provide a link to test your setup, or test it with any of the [publicly available demos](http://catalogue.fiware.org/enablers/stream-oriented-kurento/instances)?

About H264, there are some messages on the list regarding this issue. Please don't mix threads so information can be easily found by other users where expected.

**Comment by leecris** [comment] 2016-03-30 08:57
I can't provide a public demo because of our policy. I set setMaxVideoSendBandwidth(50) & setMaxVideoRecvBandwidth(50) and then video showed but still have long delay (2-3s). Both firewall disabled, open all port, setup correct stun/turn for client...

**Comment by igracia** [comment] 2016-03-30 09:48
Can you check with on the of the available demos that I linked in the previous post? Just to see if the problem is your setup, or your client.

**Comment by leecris** [comment] 2016-03-31 01:34
I tried but got error message "WebSocket connection to 'wss://kurento.lab.fiware.org:8083/call' failed: Error in connection establishment: net::ERR_TIMED_OUT"

**Comment by igracia** [comment] 2016-03-31 08:01
Which one did you try? I think it's [this](https://kurento.lab.fiware.org:8083/#) one. It's working right now. I think there was an outage last night, as I got some nagios messages in my inbox this morning. Please do try again, it should be ok now.

**Comment by leecris** [comment] 2016-03-31 08:31
I just tried your link and got same result as what I did. Presenter work fine, open new tab and click "Viewer". Nothing showed up. All graph in webrtc-internal is 0. No error in console.

**Comment by igracia** [comment] 2016-03-31 08:40
Then there's something in your client or network, as that server and app are working fine. I tried to connect, but you were signed in as presenter already. I didn't get any video back, so I guess the issue is that the presenter's video never arrives at the media server.

Can you please also try with [this](https://kurento.lab.fiware.org:8081/) more simple demo? Check both FF and Chrome, just in case, but it looks like there's something in your network.

**Comment by leecris** [comment] 2016-03-31 09:15
None of all demo worked. I'll try with few another network and feedback soon.

Thanks!

**Comment by javierlopezfernandez** [comment] 2016-03-31 10:14
kurento.lab.fiware.org host is currently experiencing huge network losses. We already contacted network administrators, but now it is not functional. I'll update this issue when network is back to normal operation

**Closed** 2016-06-03 14:11 UTC
Labels: kms
