### ISSUE TITLE
KMS 6.4.0, Image overlay memory consumption to high

### ISSUE THREAD

**Issue by robecor** [Kurento/bugtracker#34] opened 2016-02-26 07:12 UTC
Hello,
   When using the ImageOverlay filter the Memory consumption is enormous. The structure is something like this:
PlayerEndpoint(give the url from an IP camera)-->ImageOverlayFilter(with an image)-->WebRtcEndpoints of viewers. When the PlayerEndpint is connected to the filter the memory consumption start increasing at about 50MB/s and when it reaches 100%(which happens in a couple of minutes) KMS crashes and the server itself freezes. Its kinda unusable like this.
KMS version 6.4.0(but it also happened with 6.2.0)
gstreamer - 1.5
Configuration files are the default ones that come with the server installation.
I am using NodeJs and its on the same machine as Kurento.
The machine is running on an 64bit Ubuntu 14.04 and has 8GB Ram, Intel Xeon X5570 2.93Ghz 8 core.

**Comment by dfernandezlop** [comment] 2016-02-26 08:09
Hi,

Are you configuring only one image or are you changing the overlayed image several times? I have tested the filter for more than 15 minutes and the KMS memory hasn't increased. I'm going to develop a valgrind based tested to discard memory leaks in the filter.

Thank you for the report.
Regards.

**Comment by robecor** [comment] 2016-02-26 09:42
It is only one image. As long as the player endpoint is connected to that filter with the image, the memory usage keeps increasing.

**Comment by dfernandezlop** [comment] 2016-02-26 12:31
Hi,

We can't reproduce the bug. The valgrind test doesn't show any memory leak and I have executed the filter for a long time with any memory leak. Could you provide a project test? Or, at least, a KMS log to look for a strange behaviour.

Thank you.

**Comment by robecor** [comment] 2016-02-29 08:06
Sorry for the late reply!
I restarted the server with a clean log, connected the player endpoint to the image filter with a picture and closed if after a minute or to.
Here is the log.
[media-server_2016-02-29_02-58-26.00000.pid27825.zip](https://github.com/Kurento/bugtracker/files/150520/media-server_2016-02-29_02-58-26.00000.pid27825.zip)

**Comment by dfernandezlop** [comment] 2016-03-02 09:43
Hi,

I have readed your log and checking the bug.

I can say that the problem is not related with the image overlay filter but with the connection between the player (with an rtsp source) and any filter. This bug needs further investigation.

I will come back when I have new data.

Thank you for the report.
David.

**Comment by dfernandezlop** [comment] 2016-03-11 09:57
Hi,

We have fixed this bug in the development version. The problem was the filter couldn't consume all the data retrieves by the player. This data was stored and that is the reason why you saw increasing the memory.

Thanks for the report.
Best.

**Comment by igracia** [comment] 2016-03-11 10:53
@dfernandezlop Can we close this now then?

**Comment by dfernandezlop** [comment] 2016-03-11 10:55
I'm waiting for a @robecor test.

**Comment by igracia** [comment] 2016-03-11 11:03
@robecor Would you mind testing this in the development branch?

**Comment by robecor** [comment] 2016-03-16 10:43
Sorry for the late reply!
I'll test it and come back with a response.

**Comment by dfernandezlop** [comment] 2016-03-21 09:17
Hi @robecor,

Thanks for your tests. I'm going to close the bug.

Regards.

**Closed by dfernandezlop** 2016-03-21 09:17 UTC
Labels: bug, kms
