### ISSUE TITLE
KMS v6.6.0 crashes

### ISSUE THREAD

**Issue by mhassman** [Kurento/bugtracker#127] opened 2016-09-20 09:34 UTC
Hi, I've upgraded two of my kurento servers from v6.4.0 to 6.6.0 and kurento process crashed on both within 24 hours. Attaching error and log files..

**KMS Version**:
# kurento-media-server -v

Version: 6.6.0
Found modules:
        Module: 'core' version '6.6.0'
        Module: 'elements' version '6.6.0'
        Module: 'filters' version '6.6.0'

**Other libraries versions**:
# dpkg -l | egrep -i "kurento|gstreamer|nice"

ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160909144510.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.6.0.20160909201132.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.6.0.20160912112100.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.6.0.20160912114031.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.6.0.20160912115811.trusty                amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160909144510.80.gd9ef50e.trusty amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins               0.10.0.20160909214034.trusty               amd64        OpenWebRTC specific GStreamer plugins

**Client libraries**
- Language: Node.js: kurento-client
- Version: 
    "version": "6.4.0"
     "dependencies": {
  "async": "~1.2.1",
  "checktype": "^0.0.7",
  "dockerode": "2.2.6",
  "error-tojson": "0.0.1",
  "es6-promise": "^2.3.0",
  "extend": "^2.0.1",
  "inherits": "~2.0.1",
  "kurento-client-core": "6.4.0",
  "kurento-client-elements": "6.4.0",
  "kurento-client-filters": "6.4.0",
  "kurento-jsonrpc": "5.1.1",
  "minimist": "^1.1.1",
  "promisecallback": "0.0.4",
  "reconnect-ws": "github:kurentoforks/reconnect-ws#0.0.1"
  }

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: OK
- Firefox: OK
- Native: OK
  Note: This is a production system - all browsers/platforms are in use.

**System description:**
Servers are located in Europe; Clients are international.
Servers are physical 12-core; 64gb ram.
No stun/turn involved - public ip directly on servers; all udp ports allowed.

**Comment by mhassman** [comment] 2016-09-20 09:38
[cpifjve.zip](https://github.com/Kurento/bugtracker/files/482133/cpifjve.zip)

**Comment by mhassman** [comment] 2016-09-29 14:54
Hi, Apologies on the delay.

I followed this process to enable crash dump files:
   ulimit -c unlimited
   apt-get install apport
   nano /etc/apport/crashdb.conf
     add leading hash to line: 'problem_types': ['Bug', 'Package'],
   service apport restart

The following files are from two different servers - both with same physical hardware, configuration, and versions.

http://216.129.119.211/server01%2520-%2520kurento%2520server%2520failures%25202016.09.28.7z
http://216.129.119.211/server02%20-%20kurento%20server%20failures%202016.09.29.7z


fyi.. Under production load, Kurento crashes irregularly.. at times, it's up for multiple days. Other times, it crashes within minutes of starting. Definitely feels as though something in the received traffic is the cause.
Please let me know if/what else I can provide to help troubleshoot this issue.
Thnx!

**Comment by jcaden** [comment] 2016-09-29 14:57
Can you try with development version, there was a failure in 6.6.0 that is already solved there. We are working to release 6.6.1 ASAP.

**Comment by mhassman** [comment] 2016-09-29 14:59
I can test, but as these are production servers, at some point, i'll need to revert back to the stable release tree. What's the prescribed process to downgrade back to stable?
Thnx!

**Comment by jcaden** [comment] 2016-09-29 15:00
Sorry, the patch is not accepted yet, so the fix is still not present on development version.

**Comment by jcaden** [comment] 2016-09-29 15:16
This is it: https://github.com/Kurento/kms-elements/commit/0c0bdd6ed79a4a14d698cf3dfb6ee70f5952be99

Binaries are being generated right now, it could take up to 30 minutes.

**Comment by igracia** [comment] 2016-10-03 09:31
@mhassman Release is there :-) Can you check now?

**Comment by mhassman** [comment] 2016-10-07 17:04
Hi Ivan,
 
Apologies on my delay.. busy week with a new feature release.
 
I have 6.6.1 alive in my devlopment environment.. testing is positive so
far, but then again v6.6.0 tested ok here as well. This coming week, I'll
roll it into staging, then production. Baring any issues, it'll should be
under production load by the weekend.
I'll let you know how it works out.
Thnx!
:-)
 
 
-Mark


  _____

**Comment by mhassman** [comment] 2016-10-13 12:29
I've started upgrading to v6.6.1 on our production servers. First server crashed twice in the first 24hrs. So, unfortunately no noticeable stability improvement in v6.6.1.

Crash/Log files are here: http://www.hassman.org/kurento_6.6.1_crash.zip

# kurento-media-server -v
Version: 6.6.1
Found modules:
        Module: 'core' version '6.6.1'
        Module: 'elements' version '6.6.1'
        Module: 'filters' version '6.6.1'

# dpkg -l | grep gst
ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins               0.10.0.20160909214034.trusty               amd64        OpenWebRTC specific GStreamer plugins

**Comment by jcaden** [comment] 2016-10-13 12:49
It will be extremely helpful if you describe the application that you are using. From some of the logs it seems that  kms is running out of memory while trying to allocate a huge amount of memory (probably is that big because someone write on bad memory or something is not initalized), in other cases it has a segmentation fault while processing media packages.

The strange thing here is that you dont see this on your test environment. We have never seen this too. It seems that there is something in your environment that makes this happend, but without this information will be difficult to solve the problem.

**Comment by igracia** [comment] 2016-10-13 12:55
I think that your system needs a thorough review and description. I see this message

`2016-10-12 22:01:41,031245 4561 [0x00007fe187fff700]    info KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:455 WebRtcEndpointImpl()  Setting default port 3478 to stun server. Reason: No such node (modules.kurento.WebRtcEndpoint.stunServerPort)
2016-10-12 22:01:41,031370 4561 [0x00007fe187fff700]    info KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:464 WebRtcEndpointImpl()  Stun address not found in config, cannot operate behind a NAT`

which implies that you won't be able to connect clients if you are behind a NAT. I assume you have a public IP, from what I've seen in the logs. Actually, you have two IPs for that server: one public (72.5.163.31) and one private (172.22.97.31). Do you have two network cards there? All this information is important. The better you describe your system, the easier it will be for us to find the issue.

Another thing that I can read from the logs is that you create about 40 media elements (pipelines, WebRtcEndpoints and RtpEndpoints) but you only release 17 of them. It is really important that you either describe your app with detail, or that you provide a reproducer.

**Comment by mhassman** [comment] 2016-10-13 13:44
Happy to help..

The overall usage is fairly straight forward.. ingest h.264/pcmu encoded video/audio via webrtc; push this ffmpeg via rtp which transcodes to hls (h.264/aac) for consumption - i.e. one-to-many broadcast. It's similar in concept to what you've done with wowza.

Some of our dev servers have a single nic, others dual. Production servers have dual interfaces: public and private. webrtc traffic is via public; rtp is via private. There is no stun/turn in the mix. kurento.conf.json and sdp_pattern are unmodified from kurento's defaults. Kurento's install itself is generic/unmodified.

Of the things which are non-standard.. The outbound webrtc sdp (server to client) is modified in two ways: h.264 is prioritized over vp8; pcmu prioritized over vorbis. The OnIceCandidate handler only forwards non-private ip addresses. Also of note, ipv6 addressed are removed from /etc/hosts. Open files have been increased for user kurento via /etc/security/limits.conf: soft: 10248; hard: 16384. Lastly, openh264-gst-plugins-bad-1.5 is installed.

As for the number of pipelines/elements, there should be an equal number created and released. We monitor the server pipelines via servermanager - polled once per minute and we don't see the pipeline count growing. We used to release each element independently, then the pipeline, but somewhere around kurento 6.4, this caused a race condition. Since then, we release the pipeline alone. However, worth noting - we have error handling baked into the system. If there's an issue detected within the ffmpeg transcode process, we automatically kill that encoder and start a new one elsewhere in the cluster. This process will release and create a new rtp endpoint. There are retry thresholds, which when exceeded, fail the pipeline - forcing the client to re-initialize (automated as well).. which is why there can be an out of sync number of elements created/released.

As I've said before, we've only encountered this issue with production traffic - every device and network environment is encountered here. The crashes are irregular and unpredictable - sometimes multiple in a day. Other times - up for days without incident.

If there's any additional info that will help, please let me know..
Thnx!

**Comment by mhassman** [comment] 2016-10-13 13:50
Last point on server config.. since these servers are public-facing, of course we have iptables enabled..
      iptables -A INPUT -i eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      iptables -A INPUT -i eth0 -p icmp --icmp-type echo-request -j ACCEPT
      iptables -A INPUT -i eth0 -p udp --dport 1025:65535 -j ACCEPT
      iptables -P INPUT DROP

There aren't any problems with with establishing webrtc or rtp flows.. only long-term stability.

**Comment by sachinmsahrma** [comment] 2019-05-28 13:27
Hey Mhassman, 
    Have you found any solution around this? We are also facing the same issue with version 6.9.0. But we see the memory does not get free by the KMS server even after releasing all pipelines.

**Comment by j1elo** [comment] 2020-04-28 15:50
Closing; `failed to allocate 18446744072422916238 bytes` error was a GStreamer H.264 bug and got fixed since KMS 6.10

**Closed by j1elo** 2020-04-28 15:50 UTC
Labels: kms
