### ISSUE TITLE
KMS SDP videocodec config

### ISSUE THREAD

**Issue by jahKIper** [Kurento/bugtracker#84] opened 2016-06-09 06:35 UTC
We are using KMS 6.5. We want to change default value of "Maximum video bitrate", "Minimum video bitrate" and "Starting video bitrate" for KMS server(not on clients side). (https://www.webrtc-experiment.com/docs/RTP-usage.html)
We changet SdpEndpoint.conf.json like this:
  "videoCodecs" : [
    {
      "name" : "VP8/90000",
        "properties" : {
            "maxaveragebitrate": 5000,
            "maxplaybackrate": 5000
        }
    },
is it correct? or may be it's configures at another place? what kind of properties are available and how/where to apply them.

Also we found some iteresting parametrs here https://github.com/Kurento/kms-core/blob/master/src/server/interface/core.kmd.json , but we dont understand how to apply them.

**Comment by igracia** [comment] 2016-06-13 14:11
Since this is not a bug report, but a question, I'm closing the issue. Please use the list for support requests or general questions, and the bugtracker project for reporting bugs.

**Closed by igracia** 2016-06-13 14:11 UTC
