### ISSUE TITLE
Kurento 6.5.0 crash

### ISSUE THREAD

**Issue by dserrada** [Kurento/bugtracker#86] opened 2016-06-15 09:03 UTC
**KMS Version**:
Version: 6.5.0
Found modules:
        Module: 'core' version '6.5.0'
        Module: 'elements' version '6.5.0'
        Module: 'filters' version '6.5.0'

**Other libraries versions**:

ii  gstreamer1.5-libav:amd64             1.7.0.1~20160530102916.35.g90e6470.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.0~20160530103107.83.g4885bb3.trusty    amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.0~20160530103259.265.geca7cfe.trusty   amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                         6.5.0.20160530141614.trusty                amd64        Kurento core module
ii  kms-elements-6.0                     6.5.0.20160530154355.trusty                amd64        Kurento elements module
ii  kms-filters-6.0                      6.5.0.20160530155443.trusty                amd64        Kurento filters module
ii  kms-jsonrpc-1.0                      1.1.1.trusty                               amd64        Kurento jsonrpc library
ii  kmsjsoncpp                           1.6.3~20160530102631.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0             6.5.0.20160530172436.trusty                amd64        Kurento Media Server
ii  kurento-server                       6.5.0.20160530172436.trusty                amd64        Meta package for kurento server side
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.0~20160530103612.645.gb68ba3e.trusty   amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.0~20160530103212.387.g21728a3.trusty   amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.0~20160530103131.368.g0fb3a08.trusty   amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160530102934.80.gd9ef50e.trusty amd64        ICE library (shared library)

**Client libraries**
- Language: Java 
- Version: JDK 1.7.0_75
- Kurento Jar Libraries used: kurento-client-6.5.0.jar, kurento-commons-6.5.0.jar and kurento-jsonrpc-client-6.5.0.jar

**Browsers tested**
- Chrome: 51.0.2704.84 m (64-bit). FAILED

**System description:**
We are using a TURN Server for end-users (Kurento is not configured to use TURN, nor STUN), in fact TURN server is on the same machine as Kurento Media Server.

Web application is located in another machine. 

**What steps will reproduce the problem?**
- We need, at least, two users to begin recording.
- One of the users acts as "videoconference manager", we record from this user "audio & video" in webm format, no transcoding.
- Other user acts as "normal users", we just record audio from this user, also not transcoding.
- The crash only happens sometimes. We haven't found a pattern which always cause the crash, the same actions could cause the crash or not.

**What is the expected result?**
Media Server working in a normal way.

**What happens instead?**
Media Server crash

**Does it happen with one of the tutorials?**
No tested with the tutorials.

**Please provide any additional information below.**
Media server logs and core could be found in [here](https://drive.google.com/open?id=0B337fruWyOHWS0I0SWZQQWVJS0k)
Server crash trace:

Segmentation fault (thread 140176788690688, pid 21300)
Stack trace:
0x2C6D7 at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstmatroska.so
[gst_collect_pads_set_waiting]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x41B8C
[gst_collect_pads_get_type]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x3EEA9
[gst_collect_pads_pop]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x40718
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6DF85
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x75C5E
[gst_base_src_wait_playing]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x2FB65
[gst_tag_setter_get_tag_merge_mode]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x9FD7E
[g_thread_pool_new]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x712FE
[g_test_get_filename]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x70965
[start_thread]
/lib/x86_64-linux-gnu/libpthread.so.0:0x8184
[clone]
/lib/x86_64-linux-gnu/libc.so.6:0xFA37D

This bug was previously reported in the [kurento google group](https://groups.google.com/forum/#!topic/kurento/GpLvlhwGahc).

**Comment by jcaden** [comment] 2016-06-20 08:39
@rbenitez Can you create an integration test for this, please? Ask whatever details you need you reproduce the exact same situation.

**Comment by rbenitez** [comment] 2016-06-23 08:52
Hi @dserrada, I have some questions. 

1.  Which is the difference for you between "videoconference manager" and "normal users"?
2.  The "normal users" browser, is it emitting video and audio or only audio?, because in the constraint, I see that audio is true.
3. The "normal users" browser, does it receive video and audio or not?


Thanks for your answers

**Comment by dserrada** [comment] 2016-06-23 14:18
Hi @rbenitez:

   In all the videoconferences there are only one manager and one or more normal users, normally only one. All participants in the videoconference emits and receives video and audio. For all users audio is recorded (one webm file for each user), and for manager the video is recorded with the audio (in one webm file).

So the answers to your questions are:

1. The difference is only about the video recording of the videoconference. The manager's video is recorded, but for the normal users, video is not recorded.
2. Yes. Both, video and audio, are emitted . 
3. All users receives video and audio.

I hope my answers have helped you.

**Comment by rbenitez** [comment] 2016-06-23 14:22
Hi @dserrada , 

Thank you for your answers. We will do an integration test with this scenario to try of replicate  your issue.

Regards

**Comment by rbenitez** [comment] 2016-06-27 08:36
Hi @dserrada,

we have been working in this issue but we haven't been able to reproduce your problem yet. I want to confirme that the scenario is right.

All WebRtcEndpoint are created with Audio and Video and Send/Recv mode.

WebRtcEndpoint0 connects to WebRtcEndpoint1
WebRtcEndpoint0 connects to Recorder0

WebRtcEndpoint2 connects to WebRtcEndpoint3
WebRtcEndpoint2 connects to Recorder1 (With MediaProfileSpecType.WEBM_AUDIO_ONLY) 

1. When in your case, kms fails, how many time is it recording?
2. When in your case, kms fails, Do you have any order in the  creation?

Thanks 
Regards

**Comment by rbenitez** [comment] 2016-06-27 11:44
Also, If you have more kms logs with this error, please send it to us

**Comment by dserrada** [comment] 2016-06-28 07:03
Hi @rbenitez 

First, let me explain which is the workflow in the normal case of two user (manager and  normal user) and how the connections are created.

First, the two users creates end points and connect to the Kurento server in no particular order:
1. WebRtcEndpoint0 (manager) connects to WebRtcEndpoint1
2. WebRtcEndpoint2 (normal user) connects to WebRtcEndpoint3

(or in reverse order, first 2 and then 1)

Then, after both, point 1 and 2, are finished in no specific order, begins the recorder initialization phase:
3. WebRtcEndpoint0 (manager) connects to Recorder0 (With MediaProfileSpecType.WEBM)
4. WebRtcEndpoint2 (normal user) connects to Recorder1 (With MediaProfileSpecType.WEBM_AUDIO_ONLY)

(3 or 4 happens in no specific order)

We are using Kurento 6.5 in a testing environment with a low load, only 2 to 3 videoconferences at day. Since June 7 we had only two crashes, the ones we have reported.

And the answers to your questions are:
1. The first time the crash was immediately after the record begins. And about the second one, we are not sure.
2. As I told you before, there is no particular order.


Best regards.

**Comment by rbenitez** [comment] 2016-06-29 09:00
Hi @dserrada, 

we have added this [test](https://github.com/Kurento/kurento-java/blob/master/kurento-integration-tests/kurento-test/src/test/java/org/kurento/test/stability/recorder/RecorderWebRtcAudioVideoAndWebRtcOnlyAudioSimultaneous.java) in our system test. This test will execute all nights, so when we will can be able to reproduce it, we will can repair it.

Thanks

**Comment by kasperkronborg** [comment] 2016-09-01 14:02
Hi,

We have just experience the same error. We got the follow error message in the media-server_error.log:

```
(kurento-media-server:1423): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'

(kurento-media-server:1423): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(kurento-media-server:1423): GLib-GObject-CRITICAL **: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(kurento-media-server:1423): GLib-GObject-WARNING **: invalid uninstantiatable type 'audio/x-raw, layout=(string)interleaved, format=(string)S32LE' in cast to 'GObject'

(kurento-media-server:1423): GLib-GObject-WARNING **: instance of invalid non-instantiatable type 'audio/x-raw, layout=(string)interleaved, format=(string)S32LE'

(kurento-media-server:1423): GLib-GObject-CRITICAL **: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(kurento-media-server:1423): GLib-GObject-WARNING **: value "0" of type 'guint' is invalid or out of range for property 'bitrate' of type 'guint'

(kurento-media-server:1423): GLib-GObject-WARNING **: value "0" of type 'guint' is invalid or out of range for property 'bitrate' of type 'guint'

(kurento-media-server:1423): GLib-GObject-WARNING **: value "0" of type 'guint' is invalid or out of range for property 'bitrate' of type 'guint'

(kurento-media-server:1423): GLib-GObject-WARNING **: value "0" of type 'guint' is invalid or out of range for property 'bitrate' of type 'guint'

(kurento-media-server:1423): GLib-GObject-WARNING **: value "0" of type 'guint' is invalid or out of range for property 'bitrate' of type 'guint'
Segmentation fault (thread 140021545617152, pid 1423)
Stack trace:
0x291AF at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstmatroska.so
[gst_collect_pads_set_waiting]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x4250C
[gst_collect_pads_get_type]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x3F829
[gst_collect_pads_pop]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x41098
[gst_flow_get_name]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x6E4F7
[gst_pad_push]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0x7649E
[gst_base_src_wait_playing]
/usr/lib/x86_64-linux-gnu/libgstbase-1.5.so.0:0x30075
[gst_tag_setter_get_tag_merge_mode]
/usr/lib/x86_64-linux-gnu/libgstreamer-1.5.so.0:0xA04BE
[g_thread_pool_new]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x712FE
[g_test_get_filename]
/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x70965
[start_thread]
/lib/x86_64-linux-gnu/libpthread.so.0:0x8182
[clone]
/lib/x86_64-linux-gnu/libc.so.6:0xFA47D
```

We have never seen this before and it happened to us after we had changed from MP4 recording to WebM recording. We had 30 different people trying to connect from the browser to the server with both video and audio. Around half of them had connected when the error happened. Running a `top` command on the Ubuntu server told us that the `apport` command was using 100% CPU for the kurento process.

We run Kurento Media Server 6.4.0.

Anyway to get a more specific explanation for this error?

Thanks

**Comment by j1elo** [comment] 2020-04-28 13:14
Closing this as old bug. Please reopen if the issue still happens with latest versions of KMS.

**Closed by j1elo** 2020-04-28 13:14 UTC
Labels: bug, kms
