### ISSUE TITLE
Kurento media server keeps connections open after the end of the video session.

### ISSUE THREAD

**Issue by IonHubber** [Kurento/bugtracker#253] opened 2018-06-01 12:43 UTC
**KMS Version**: 
Kurento Media Server version: 6.7.1
Found modules:
        'core' version 6.7.1
        'elements' version 6.7.1
        'filters' version 6.7.1

**Other libraries versions**:
ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
ii  kms-core                             6.7.1.trusty.20180322151212.47e0370        amd64        Kurento Core module
ii  kms-elements                         6.7.1.trusty.20180322161851.5aaf4a0        amd64        Kurento Elements module
ii  kms-filters                          6.7.1.trusty.20180322170020.7f2d045        amd64        Kurento Filters module
ii  kms-jsonrpc                          6.7.1.trusty~20180322150101.1.637bf2a      amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3.trusty.20170725122830.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.7.1.trusty.20180322174246.dd49a2c        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (shared library)
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from openh264

**Client libraries**
- Language: Java
- Version: 1.8

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: OK
- Firefox: OK
- Native: OK

**System description:**
KMS located on the same computer where is the kurento-tutorial-java started.

**What steps will reproduce the problem?**
1. Start video recording.
2. Stop video recording.
3. Close browser.

**What is the expected result?**
Websocket connection from browser is closed, stream connection on KMS is destroyed.

**What happens instead?**
Websocket connection from browser is closed, stream connection on KMS is live.

**Does it happen with one of the tutorials?**
Yes. 'kurento-tutorial-java'  6.7.1

**Please provide any additional information below.**
Each new video record/play connection init unix stream connection. After the end user session (closing browser, for example) stream connection not destroyed. At the end we can see 5k+ active connections and more.

netstat  -anpl | grep kurento-media | grep unix | wc -l

unix  3      [ ]         STREAM     CONNECTED     369547 26730/kurento-media
unix  3      [ ]         STREAM     CONNECTED     369269 26730/kurento-media
unix  3      [ ]         STREAM     CONNECTED     364356 26730/kurento-media
unix  3      [ ]         STREAM     CONNECTED     373253 26730/kurento-media
unix  3      [ ]         STREAM     CONNECTED     370551 26730/kurento-media
unix  3      [ ]         STREAM     CONNECTED     373006 26730/kurento-media
unix  3      [ ]         STREAM     CONNECTED     364093 26730/kurento-media 
...

**Comment by jlongman** [comment] 2018-06-06 15:54
Did you destroy the pipelines?

**Comment by IonHubber** [comment] 2018-06-08 10:59
You are right. I do not destroy pipeline. I added follow lines:
`// HelloWorldRecHandler.java 
...
case "stop":
        if (user != null) {
          user.stop();
// new line
          user.release();
        }
        break;
...

//UserSession.java
...
public void release() {
   this.mediaPipeline.release();
    this.webRtcEndpoint = null;
//new line
    this.recorderEndpoint = null;
    this.mediaPipeline = null;
    if (this.stopTimestamp == null) {
      this.stopTimestamp = new Date();
    }
}
...
`
Some of connections destroyed now. But after end of record/play activity I still have unidentified connections:

netstat  -anp | grep kur
tcp6       0      0 :::8888                 :::*                    LISTEN      32513/kurento-media
tcp6       0      0 127.0.0.1:8888          127.0.0.1:59022         ESTABLISHED 32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     197579   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     197593   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     198573   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     198574   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     197578   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     199700   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     197594   32513/kurento-media
unix  3      [ ]         STREAM     CONNECTED     199699   32513/kurento-media

There is correlation by number in lsof with following:

KmsLoop   32513 32612    kurento   12u     unix 0xffff880078c28000       0t0     197578 socket
KmsLoop   32513 32612    kurento   13u     unix 0xffff880078c2bc00       0t0     197579 socket
KmsLoop   32513 32612    kurento   17u     unix 0xffff880078c29e00       0t0     197593 socket
KmsLoop   32513 32612    kurento   18u     unix 0xffff880078c2a580       0t0     197594 socket
KmsLoop   32513 32612    kurento   19u     unix 0xffff880029828000       0t0     198573 socket
KmsLoop   32513 32612    kurento   20u     unix 0xffff880029829e00       0t0     198574 socket
KmsLoop   32513 32612    kurento   21u     unix 0xffff8800298283c0       0t0     199699 socket
KmsLoop   32513 32612    kurento   22u     unix 0xffff88002982a940       0t0     199700 socket
GstSystem 32513 32617    kurento   12u     unix 0xffff880078c28000       0t0     197578 socket
GstSystem 32513 32617    kurento   13u     unix 0xffff880078c2bc00       0t0     197579 socket
GstSystem 32513 32617    kurento   17u     unix 0xffff880078c29e00       0t0     197593 socket
GstSystem 32513 32617    kurento   18u     unix 0xffff880078c2a580       0t0     197594 socket
GstSystem 32513 32617    kurento   19u     unix 0xffff880029828000       0t0     198573 socket
GstSystem 32513 32617    kurento   20u     unix 0xffff880029829e00       0t0     198574 socket
GstSystem 32513 32617    kurento   21u     unix 0xffff8800298283c0       0t0     199699 socket
GstSystem 32513 32617    kurento   22u     unix 0xffff88002982a940       0t0     199700 socket

What is 'KmsLoop' and 'GstSystem'? Thanks.

**Comment by ifplusor** [comment] 2020-04-20 22:57
@jlongman Why kurento do not close socket before destroy MediaPipeline but WebrtcEndpoint is release?

**Comment by j1elo** [comment] 2020-04-21 10:05
Wait until the Kurento garbage collector runs, to see if the sockets are released. By default the garbage collector runs every 240 seconds.

Change the [Debug Logging](https://doc-kurento.readthedocs.io/en/latest/features/logging.html) to add this: `KurentoMediaSet:5`

Now you should be able to see DEBUG messages from the MediaSet class. Then wait for this message:
```
Running garbage collector
```

**Comment by ifplusor** [comment] 2020-04-25 21:03
@j1elo I saw "Running garbage collector" in log, but socket not close after that time. And after release MediaPipeline, it also not close.

**Comment by j1elo** [comment] 2020-04-26 17:23
We've been doing some analysis and here: https://github.com/Kurento/bugtracker/issues/460

**Comment by j1elo** [comment] 2020-04-26 17:23
Duplicate of #460

**Closed by j1elo** 2020-04-26 17:23 UTC

**Comment by ifplusor** [comment] 2020-04-27 02:38
> We've been doing some analysis and here: #460

Thank you.
