### ISSUE TITLE
RTPendpoint.processOffer\Answer ignores incoming SDP and environment variables 

### ISSUE THREAD

**Issue by RobotnickIsrael** [Kurento/bugtracker#477] opened 2020-05-20 10:23 UTC
## Prerequisites
* [V] I have read the SUPPORT document, kurento blogs and mailing groups
* [V] I have checked the Troubleshooting Guide
* [V] Using KMS 6.13 (almost latest and changesin 6.13.2 are not related)

## Issue description

[According to Ivan Gracia](https://groups.google.com/forum/#!msg/kurento/I8Jr-Lfa7Qo/9kDF-4FaBAAJ), rtpEP.processAnswer() should use the answer and change it's IP \ port.
Also, since KMS has "KMS_EXTERNAL_ADDRESS", you would expect it to be used on the SDP as well.
Currently the IP that the KMS gives out is the inner IP, not the external - which is wrong by the SDP protocol:
["A local IP address
      MUST NOT be used in any context where the SDP description might
      leave the scope in which the address is meaningful (for example, a
      local address MUST NOT be included in an application-level
      referral that might leave the scope)."](https://tools.ietf.org/html/rfc4566)

## Context
This impacts two things:
A. If the sdp leaves the inner network - the ip wont be reachable.
B. Older cameras and accessories that don't use RTSP - They do not have the ability to negotiate
their sending port. They only broadcast multicast\unicast to one or more addresses and IP and
it's up to the media receiver to listen to the right ip+port. [This is described by kurento ffmpeg tutorial - **first send with ffmpeg** and than listen to it](https://www.kurento.org/blog/rtp-ii-streaming-ffmpeg)

It's not possible to set this port before kms runs in [base.rtp.config.ini](https://doc-kurento.readthedocs.io/en/latest/_static/client-javadoc/org/kurento/client/BaseRtpEndpoint.html) since it's not possible to know the port in advance, and limiting to one will do troubles with the webRTC port.
It's not possible to use [autoPort discovery as described by kurento](https://doc-kurento.readthedocs.io/en/6.9.0/features/nat_traversal.html#features-comedia) since the passive server is the one behind the NAT, and it still randomly generates a port.

Adding Symmetric RTP as described on [kurento blogs](https://www.kurento.org/blog/rtp-ii-streaming-ffmpeg) doesn't  change the SDP answer as well. (Not by adding the local port+ip to ffmpeg and not [by adding "a=direction:active" to the sdp as described by kurento.](https://doc-kurento.readthedocs.io/en/6.9.0/knowledge/rtp_streaming.html)

## How to reproduce?
Activate KMS with: KMS_EXTERNAL_ADDRESS=<your external ip>
Create a pipeline as follows: RTPendpoint->WEBRTCEndpoint
Process sdp's as described below.

## Expected & current behavior

When using Ivan Gracia tip to generateOffer and use the answer:

//*code example*
const ignoringSDPfromKMS = await rtpEndpoint.generateOffer();
rtpEndpoint.processAnswer(rtpSDPoffer, (err, sdpAnswer) => {...}
//*end of code example*

The KMS answer ignores the externalIP that was inserted (uses local ip) and
ignores the ip+port in c=... on the SDP offer:

rtp sdp offer from camera:
v=0
o=- 0 0 IN IP4 10.0.233.150
s=Israel RTP N_VM 5004
c=IN IP4 10.0.232.155
t=0 0
a=tool:libavformat 58.10.100
m=video 5004 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264/90000
a=ssrc:112233 cname:someName@test.io
a=fmtp:96 packetization-mode=1

rtp sdp answer from kms:
v=0
o=- 3798943271 3798943271 IN IP4 172.99.14.1
s=Kurento Media Server
c=IN IP4 172.99.14.1
t=0 0
m=video 39928 RTP/AVPF 96
a=setup:actpass
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:96 H264/90000
a=sendrecv
a=mid:video0
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
a=ssrc:1118671240 cname:user1242910925@host-8a5455e3
a=rtcp:39929

The same thing happens when adding direction and changing "sendonly" to "sendrecv".

The same thing happens when using process.Offer. Again, changing to "sendRecv" or 
a=direction:active" does not make the KMS offer the IP and PORT you would expect.

//*code example*
//const ignoringSDPfromKMS = await rtpEndpoint.generateOffer();
rtpEndpoint.processOffer(rtpSDPoffer, (err, sdpAnswer) => {...}
//*end of code example*

rtp sdp offer from camera:
v=0
o=- 0 0 IN IP4 10.0.233.150
s=Israel RTP N_VM 5004
c=IN IP4 10.0.232.155
t=0 0
a=tool:libavformat 58.10.100
m=video 5004 RTP/AVP 96
a=sendonly
a=rtpmap:96 H264/90000
a=ssrc:112233 cname:someName@test.io
a=fmtp:96 packetization-mode=1

rtp sdp answer from kms:
v=0
o=- 3798943163 3798943163 IN IP4 172.99.14.1
s=Kurento Media Server
c=IN IP4 172.99.14.1
t=0 0
a=tool:libavformat 58.10.100
m=video 48580 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=ssrc:2007176750 cname:user2009946514@host-c9b6c2a
a=rtcp:48581

Expected:
KMS should listen to port 5004 as described (because asking for symmetric).
KMS SDP should include externalIP and 5004 port.

I must add that if I send my udp to the external address (which I already know)
and the port that I got from the answer that the SDP is listening too - then the video
works great. So the problem is only technical:
SDP has wrong IP inside (inner instead of external)
KMS and SDP doesn't update port. (randomly chooses instead of using what's given)

## (Optional) Possible solution
Fix should be rather simple:
1. When creating the SDP in processOffer \ generateOffer \ processAnswer - use the external IP
given to KMS instead of looking for it.
2. When creating the SDP in processOffer \ generateOffer - better to have additional input to the function to use a specific port instead of randomly selecting port.
I read a lot of documentation about SDP and when sending "sendonly" the port under "m=..." I think is still for incoming and not outgoing packets. (And of course it's true for recv as well).

This is super important ability (to pre-select listening port) asked by so many users (I found this question many times and people are always lost, and Gracia's solution to this doesn't work) that should be very easy to implement.

### INFO about Kurento Media Server

* Kurento version:  6.13
* Server OS:        CentOS Linux 7 Kernel 3.10.0-957.el7.x86_64
* Installation method:    
    [X] Docker

### INFO about your Application Server

* Language:                 Node.js
* Kurento Client version:   6.13

### INFO about end-user clients

* Device(s):    PC
* OS(es):       Windows
* Browser(s):   Chrome 73

## INFO about your environment
- KMS_EXTERNAL_ADDRESS=10.0.232.155 added to the docker-compose.yaml

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by RobotnickIsrael** [comment] 2020-05-20 10:28
P.S: In the [media-soup demo](https://github.com/Kurento/mediasoup-demos/blob/3668a3cfe8bc53e00af3aa20569ba6e7515082df/mediasoup-kurento-filter/server.js#L407), there is a use of symmetric RTP (same port for both incoming and outgoing packages). But again the requested port from media-soup is ignored, and after processing the SDP Answer from KMS the code updates medias-soup for the new port. 
Why not use (if port isn't taken of course) the same port as already requested? Since we want to do it symmetric it makes sense to use the port already pre-given to us as their output - with our input.

**Comment by RobotnickIsrael** [comment] 2020-05-20 14:31
P.P.S: I didn't test multi-cast yet, but if kurento sdp-offer acts the same with multi-cast, than it's 100% a bug. KMS can't send a multicast sender a new port for multi-cast, since it's not the only one listening to it. I'll try testing the behavior in multicast soon.

**Comment by RobotnickIsrael** [comment] 2020-05-21 06:04
I checked what's going on with multi-cast and it's the same problem.
I generated a sdp file with ffmpeg to multi cast, and sent it to rtpEndPoint.processOffer(sdp)
ffmpeg streams to 239.0.0.1 with ttl 13 and port 5004 
Kms returns local IP which is wrong, and listens to whatever ports it want and of course multicast signal isn't just for kurento - and pre-opened and used by many different servers on the network.

rtp sdp offer from camera:
v=0
o=- 0 0 IN IP4 10.0.233.150
s=Israel RTP N_VM 5004
c=IN IP4 239.0.0.1/13
t=0 0
a=tool:libavformat 58.10.100
m=video 5004 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=sendonly
a=ssrc:112233 cname:someName@test.io


rtp sdp answer from kms:
v=0
o=- 3798976865 3798976865 IN IP4 172.99.17.1
s=Kurento Media Server
c=IN IP4 172.99.17.1
t=0 0
a=tool:libavformat 58.10.100
m=video 42160 RTP/AVP 96
a=recvonly
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=ssrc:501996286 cname:user2098744607@host-f39668bd
a=rtcp:42161

**Comment by j1elo** [comment] 2020-06-18 12:52
The `ExternalAddress` parameter only applies to WebRtcEndpoint. Its documentation has been updated to clarify that it should only be used under controlled circumstances and by advanced users. API docs: [Java](https://doc-kurento.readthedocs.io/en/latest/_static/client-javadoc/org/kurento/client/WebRtcEndpoint.html#setExternalAddress-java.lang.String-), [Javascript](https://doc-kurento.readthedocs.io/en/latest/_static/client-jsdoc/module-elements.WebRtcEndpoint.html#setExternalAddress). In any case, it is just a hack to manipulate the local ICE candidates that are gathered by the WebRtcEndpoint.

RtpEndpoint has no information about what is the external or public IP address of the machine where it is running. As such, it can only do a best effort and put the local private IP of the network interface where it will be listening for incoming packets.

If the SDP leaves the inner network, then the Application should mangle the SDP and (by whatever means) know the external network address and put it in.

For devices and software that doesn't have the ability to negotiate their sending port, the intermediate Application needs to do SDP mangling as appropriate. The [RTP Receiver tutorial](https://doc-kurento.readthedocs.io/en/latest/tutorials/java/tutorial-rtp-receiver.html) shows an example of this.

Closing as not a bug.

**Closed by j1elo** 2020-06-18 12:52 UTC
Labels: not-a-bug
