### ISSUE TITLE
How to solve the problem with support in internet explorer, safari and edge?

### ISSUE THREAD

**Issue by maranqz** [Kurento/bugtracker#20] opened 2015-12-19 17:19 UTC

**Comment by igracia** [comment] 2015-12-21 09:23
I'm closing this as it is not a bug, but something that should go (and has been [discussed already](https://groups.google.com/forum/#!searchin/kurento/explorer) in the [public mailing list](https://groups.google.com/forum/#!forum/kurento). Please read the [guidelines](https://github.com/Kurento/bugtracker/blob/master/README.md) on how to report bugs, and where to look before reporting a bug.

**Closed by igracia** 2015-12-21 09:23 UTC
