### ISSUE TITLE
KMS-6.7.0 not working when ufw is installed and enabled in ubuntu 16.04

### ISSUE THREAD

**Issue by ayushjn20** [Kurento/bugtracker#227] opened 2018-02-01 23:00 UTC
**KMS Version**:6.7.0~1.g6ebaa27

**Other libraries versions**:
        Module: 'core' version '6.6.3'
	Module: 'elements' version '6.6.3'
	Module: 'filters' version '6.7.0~1.g0314843'

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

```
ii  gstreamer1.5-libav:amd64                                 1.8.2.1.xenial~20170725171352.96.493eee4     amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64                                  0.1.13.1.xenial~20170725160546.81.eebfdab    amd64        ICE library (GStreamer plugin)
ii  gstreamer1.5-plugins-bad:amd64                           1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64                          1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64                          1.8.1.1.xenial~20170725161537.112.9ee4248    amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64                          1.8.1.1.xenial~20170725170621.89.2685b0f     amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64                            1.8.1.1.xenial~20170725161537.112.9ee4248    amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                                     1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer plugins for X11 and Pango
ii  kms-core-6.0                                             6.6.3.xenial.20170811182512.2704d13          amd64        Kurento core module
ii  kms-elements-6.0                                         6.6.3.xenial.20170812234356.9e3fff4          amd64        Kurento elements module
ii  kms-filters-6.0                                          6.7.0.xenial~20170813001324.1.0314843        amd64        Kurento filters module
ii  kms-jsonrpc-1.0                                          1.2.0.xenial~20170811181902.1.8cee9d8        amd64        Kurento jsonrpc library
ii  kmsjsoncpp                                               1.6.3.xenial.20170725151047.d78deb7          amd64        Kurento jsoncpp library
ii  kurento-media-server-6.0                                 6.7.0.xenial~20170813003033.1.6ebaa27        amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64                      1.8.1.1.xenial~20170725164047.100.3db37b1    amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64                     1.8.1.1.xenial~20170725154709.55.7b19cfd     amd64        GStreamer libraries from the "base" set
ii  libgstreamer0.10-0:amd64                                 0.10.36-1.5ubuntu1                           amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0:amd64                                  1.8.1.1.xenial~20170725152356.170.0d6031b    amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                                          0.1.13.1.xenial~20170725160546.81.eebfdab    amd64        ICE library (shared library)
ii  libreoffice-avmedia-backend-gstreamer                    1:5.1.6~rc2-0ubuntu1~xenial2                 amd64        GStreamer backend for LibreOffice


```
**Client libraries**
- Language: Node.js (kurento-client)
- Version: kurento-client@6.6.1-dev (git://github.com/kurento/kurento-client-js.git#efb160e85a4b1f376307fe1979c9fbcb5f978393)

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome: FAIL
- Firefox: FAIL
- Native:

**System description:**
 - Listening on 8888 port.
 - Same configuration as mentioned in documentation
 - installed on default location using apt ppa.
 - node.js (express app) served on the same machine
 - kms ws_uri: `ws://localhost:8888/kurento`

**What steps will reproduce the problem?**
1. Disable ufw, and run kms service and the node app, the app will work fine.
2. Enable ufw, open all relevant ports and all ports for UDP networking. The node server won't connect
3. Enable ufw, reset all rules and allow everything -- incoming,outgoing and routing, the app won't connect
4. Checking ws connection using [Simple WebSocket Client](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=en) Same case, works fine with ufw disabled, but won't connect when enabled (although everything is allowed through it.)
5. Once the app is being stopped or hindered in some mysterious way by ufw, I can't simply disable ufw and restart kms service and get all things work. I have to **reboot** the system.

**What is the expected result?**
UFW shouldn't hinder localhost connection but still it is doing.

**Does it happen with one of the tutorials?**
Tested with one-to-many nodejs tutorial, doesn't changes anything.

**Additional Information**

**tcpdump output:**
`tcpdump -vv -i lo port 8888 and '(tcp-syn|tcp-ack)!=0'`
 - **when successful**

```
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 
    262144 bytes
    13:04:30.904489 IP (tos 0x0, ttl 64, id 51739, offset 0, flags [DF], 
    proto TCP (6), length 316)
    localhost.48866 > localhost.8888: Flags [P.], cksum 0xff30 (incorrect 
    -> 0xf928), seq 1016466694:1016466958, ack 1363142683, win 3637, 
    options [nop,nop,TS val 2501898228 ecr 2501846491], length 264
    13:04:30.904729 IP (tos 0x0, ttl 64, id 51740, offset 0, flags [DF], 
    proto TCP (6), length 298)
    localhost.48866 > localhost.8888: Flags [P.], cksum 0xff1e (incorrect 
    -> 0xc0e7), seq 264:510, ack 1, win 3637, options [nop,nop,TS val 
    2501898228 ecr 2501846491], length 246
    13:04:30.906243 IP (tos 0x0, ttl 64, id 43249, offset 0, flags [DF], 
    proto TCP (6), length 52)
    localhost.8888 > localhost.48866: Flags [.], cksum 0xfe28 (incorrect -
    > 0x009f), seq 1, ack 510, win 1891, options [nop,nop,TS val 
    2501898228 ecr 2501898228], length 0
    13:04:30.906293 IP (tos 0x0, ttl 64, id 43250, offset 0, flags [DF], 
    proto TCP (6), length 155)
    localhost.8888 > localhost.48866: Flags [P.], cksum 0xfe8f (incorrect 
    -> 0xd653), seq 1:104, ack 510, win 1891, options [nop,nop,TS val 
    2501898230 ecr 2501898228], length 103

```

 - **when failed**

```
    tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 
    262144 bytes
    13:13:14.951036 IP (tos 0x0, ttl 64, id 22976, offset 0, flags [DF], 
    proto TCP (6), length 60)
    localhost.53530 > localhost.8888: Flags [S], cksum 0xfe30 (incorrect -
    > 0x270b), seq 3285074519, win 43690, options [mss 65495,sackOK,TS val 
    2502422275 ecr 0,nop,wscale 7], length 0
    13:13:22.531679 IP (tos 0x0, ttl 64, id 28371, offset 0, flags [DF], 
    proto TCP (6), length 60)
    localhost.55238 > localhost.8888: Flags [S], cksum 0xfe30 (incorrect -
    > 0x1a57), seq 3772583348, win 43690, options [mss 65495,sackOK,TS val 
    2502429855 ecr 0,nop,wscale 7], length 0
    13:13:23.559036 IP (tos 0x0, ttl 64, id 28372, offset 0, flags [DF], 
    proto TCP (6), length 60)
    localhost.55238 > localhost.8888: Flags [S], cksum 0xfe30 (incorrect -
    > 0x1654), seq 3772583348, win 43690, options [mss 65495,sackOK,TS val 
    2502430882 ecr 0,nop,wscale 7], length 0
    13:13:25.575055 IP (tos 0x0, ttl 64, id 28373, offset 0, flags [DF], 
    proto TCP (6), length 60)
    localhost.55238 > localhost.8888: Flags [S], cksum 0xfe30 (incorrect -
    > 0x0e74), seq 3772583348, win 43690, options [mss 65495,sackOK,TS val 
    2502432898 ecr 0,nop,wscale 7], length 0
    13:13:29.799248 IP (tos 0x0, ttl 64, id 28374, offset 0, flags [DF], 
    proto TCP (6), length 60)
    localhost.55238 > localhost.8888: Flags [S], cksum 0xfe30 (incorrect -
    > 0xfdf2), seq 3772583348, win 43690, options [mss 65495,sackOK,TS val 
    2502437123 ecr 0,nop,wscale 7], length 0
    13:13:37.990986 IP (tos 0x0, ttl 64, id 28375, offset 0, flags [DF], 
    proto TCP (6), length 60)
    localhost.55238 > localhost.8888: Flags [S], cksum 0xfe30 (incorrect -
    > 0xddf3), seq 3772583348, win 43690, options [mss 65495,sackOK,TS val 
    2502445314 ecr 0,nop,wscale 7], length 0

```

**Comment by jlongman** [comment] 2018-02-09 15:54
This sounds like a UFW problem?

**Comment by ayushjn20** [comment] 2018-02-09 16:09
No, I later found that the issue is related with [websocketpp](https://github.com/zaphoyd/websocketpp) that is being used in kurento-media-server. The relevant information is explained [here](https://stackoverflow.com/questions/48557856/ufw-not-allowing-kurento-media-server-6-7-to-get-connected-through-ws-uri). So, the issue has to wait till the release of new stable version of websocketpp.

**Comment by j1elo** [comment] 2020-05-08 14:57
Duplicate of #245

**Comment by j1elo** [comment] 2020-05-08 14:58
This issue was studied here: https://github.com/Kurento/bugtracker/issues/245
And solved with commit https://github.com/Kurento/kurento-media-server/commit/1c95be3bbe4434d3edf2432fb07cd1d7e156b8db

**Closed by j1elo** 2020-05-08 14:58 UTC
