### ISSUE TITLE
Allow Kurento to use STUN server domain names

### ISSUE THREAD

**Issue by jbabob** [Kurento/bugtracker#442] opened 2020-03-05 20:22 UTC
## Prerequisites

* [x] I have read the SUPPORT document
  

* [x] I have checked the Troubleshooting Guide
  

* [x] I have tested with the latest version
  

## Issue description

Forcing the use of IP addresses when configuring STUN servers in Kurento Media Server makes using public STUN servers unreliable, as their public IP addresses may change at any given time. Using a domain name instead would be more desirable.

## Context

Using a public STUN server rather than making one ourselves would work better for our needs. We used the IP address for stun.l.google.com. It worked until that IP changed a day later.

## How to reproduce?
 
N/A

## Expected & current behavior

Configuring the STUN server with a domain name works.

## Environment info

Any

### INFO: Kurento Media Server

* Kurento version:  
* Server OS:        
* Installation method:
    
  - [ ] apt-get
    
  - [x] Docker
    
  - [ ] AWS
    
  - [ ] Built from sources
    

### INFO: Application Server

* Language:                 
* Kurento Client version:   

### INFO: End-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Version details

```
kurento-media-server -v

lsb_release -a

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```

**Comment by jbabob** [comment] 2020-03-10 17:44
Any news on that?

**Comment by micaelgallego** [comment] 2020-03-11 13:09
It is a good feature request. 

We will evaluate it to be considered in the future.

**Comment by j1elo** [comment] 2020-03-11 13:35
Closing: not a bug.

FYI this should be implemented in **libnice**, the underlying 3rd-party library we use for STUN. They even have already a feature request, although without much movement. Maybe you can help them by contributing some code:

[Add support for name resolution of servers](https://gitlab.freedesktop.org/libnice/libnice/issues/11)

Lastly, a note: we recommend not relying on public & free STUN servers, which tend to be very unreliable (which is normal considering they are provided by third parties free of charge). Supporting this use case is not a priority of ours, as it would probably end up meaning more issue reports on our side.

**Closed by j1elo** 2020-03-11 13:35 UTC
Labels: enhancement
